// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package storage

import (
	"database/sql"
)

type User struct {
	ID        int32
	FirstName string
	LastName  string
	Phone     string
	Email     string
	Username  string
	Password  string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
	DeletedAt sql.NullInt64
}
