// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package storage

import (
	"context"
)

const checkEmailExists = `-- name: CheckEmailExists :one
SELECT EXISTS (
    SELECT 1 FROM users
    WHERE email = $1 AND deleted_at = 0
)
`

func (q *Queries) CheckEmailExists(ctx context.Context, email string) (bool, error) {
	row := q.db.QueryRowContext(ctx, checkEmailExists, email)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createUser = `-- name: CreateUser :exec
INSERT INTO users
(
    first_name,
    last_name,
    phone,
    email,
    username,
    password
) VALUES (
    $1, $2, $3, $4, $5, $6
)
`

type CreateUserParams struct {
	FirstName string
	LastName  string
	Phone     string
	Email     string
	Username  string
	Password  string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.ExecContext(ctx, createUser,
		arg.FirstName,
		arg.LastName,
		arg.Phone,
		arg.Email,
		arg.Username,
		arg.Password,
	)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
UPDATE users
SET deleted_at = EXTRACT(EPOCH FROM NOW())
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const getPasswordWithId = `-- name: GetPasswordWithId :one
SELECT password FROM users
WHERE id = $1
`

func (q *Queries) GetPasswordWithId(ctx context.Context, id int32) (string, error) {
	row := q.db.QueryRowContext(ctx, getPasswordWithId, id)
	var password string
	err := row.Scan(&password)
	return password, err
}

const getUserById = `-- name: GetUserById :one
SELECT 
    id,
    first_name,
    last_name,
    phone,
    email,
    username
FROM users
WHERE id = $1 and deleted_at = 0
`

type GetUserByIdRow struct {
	ID        int32
	FirstName string
	LastName  string
	Phone     string
	Email     string
	Username  string
}

func (q *Queries) GetUserById(ctx context.Context, id int32) (GetUserByIdRow, error) {
	row := q.db.QueryRowContext(ctx, getUserById, id)
	var i GetUserByIdRow
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Phone,
		&i.Email,
		&i.Username,
	)
	return i, err
}

const getUsers = `-- name: GetUsers :many
SELECT 
    id,
    first_name,
    last_name,
    phone,
    email,
    username
FROM users WHERE deleted_at = 0
`

type GetUsersRow struct {
	ID        int32
	FirstName string
	LastName  string
	Phone     string
	Email     string
	Username  string
}

func (q *Queries) GetUsers(ctx context.Context) ([]GetUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, getUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUsersRow
	for rows.Next() {
		var i GetUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.FirstName,
			&i.LastName,
			&i.Phone,
			&i.Email,
			&i.Username,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const signIn = `-- name: SignIn :one
SELECT id, password FROM users
WHERE username = $1 AND deleted_at = 0
`

type SignInRow struct {
	ID       int32
	Password string
}

func (q *Queries) SignIn(ctx context.Context, username string) (SignInRow, error) {
	row := q.db.QueryRowContext(ctx, signIn, username)
	var i SignInRow
	err := row.Scan(&i.ID, &i.Password)
	return i, err
}

const updatePasswordWithEmail = `-- name: UpdatePasswordWithEmail :exec
UPDATE users
SET password = $2
WHERE email = $1 and deleted_at = 0
`

type UpdatePasswordWithEmailParams struct {
	Email    string
	Password string
}

func (q *Queries) UpdatePasswordWithEmail(ctx context.Context, arg UpdatePasswordWithEmailParams) error {
	_, err := q.db.ExecContext(ctx, updatePasswordWithEmail, arg.Email, arg.Password)
	return err
}

const updatePasswordWithId = `-- name: UpdatePasswordWithId :exec
UPDATE users
SET password = $2
WHERE id = $1 and deleted_at = 0
`

type UpdatePasswordWithIdParams struct {
	ID       int32
	Password string
}

func (q *Queries) UpdatePasswordWithId(ctx context.Context, arg UpdatePasswordWithIdParams) error {
	_, err := q.db.ExecContext(ctx, updatePasswordWithId, arg.ID, arg.Password)
	return err
}

const updateUser = `-- name: UpdateUser :exec
UPDATE users
SET first_name = $2,
    last_name = $3,
    phone = $4,
    email = $5,
    username = $6
WHERE id = $1 AND deleted_at = 0
`

type UpdateUserParams struct {
	ID        int32
	FirstName string
	LastName  string
	Phone     string
	Email     string
	Username  string
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.ExecContext(ctx, updateUser,
		arg.ID,
		arg.FirstName,
		arg.LastName,
		arg.Phone,
		arg.Email,
		arg.Username,
	)
	return err
}
