// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package storage

import (
	"context"
)

const createComment = `-- name: CreateComment :exec
INSERT INTO comments
(
    user_id,
    post_id,
    content
) VALUES (
    $1, $2, $3
)
`

type CreateCommentParams struct {
	UserID  int64
	PostID  int64
	Content string
}

func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) error {
	_, err := q.db.ExecContext(ctx, createComment, arg.UserID, arg.PostID, arg.Content)
	return err
}

const deleteComment = `-- name: DeleteComment :exec
UPDATE comments
SET deleted_at = EXTRACT(EPOCH FROM NOW())
WHERE id = $1
`

func (q *Queries) DeleteComment(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteComment, id)
	return err
}

const getCommentByPostId = `-- name: GetCommentByPostId :many
SELECT 
    id,
    user_id,
    post_id,
    content
FROM comments
WHERE post_id=$1 and deleted_at = 0
`

type GetCommentByPostIdRow struct {
	ID      int32
	UserID  int64
	PostID  int64
	Content string
}

func (q *Queries) GetCommentByPostId(ctx context.Context, postID int64) ([]GetCommentByPostIdRow, error) {
	rows, err := q.db.QueryContext(ctx, getCommentByPostId, postID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCommentByPostIdRow
	for rows.Next() {
		var i GetCommentByPostIdRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.PostID,
			&i.Content,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCommentByUserId = `-- name: GetCommentByUserId :many
SELECT 
    id,
    user_id,
    post_id,
    content
FROM comments
WHERE user_id=$1 and deleted_at = 0
`

type GetCommentByUserIdRow struct {
	ID      int32
	UserID  int64
	PostID  int64
	Content string
}

func (q *Queries) GetCommentByUserId(ctx context.Context, userID int64) ([]GetCommentByUserIdRow, error) {
	rows, err := q.db.QueryContext(ctx, getCommentByUserId, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCommentByUserIdRow
	for rows.Next() {
		var i GetCommentByUserIdRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.PostID,
			&i.Content,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateComment = `-- name: UpdateComment :exec
UPDATE comments
SET content = $2
WHERE id = $1 AND deleted_at=0
`

type UpdateCommentParams struct {
	ID      int32
	Content string
}

func (q *Queries) UpdateComment(ctx context.Context, arg UpdateCommentParams) error {
	_, err := q.db.ExecContext(ctx, updateComment, arg.ID, arg.Content)
	return err
}
