// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.12
// source: protos/course.proto

package coursepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Course struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Category      string                 `protobuf:"bytes,5,opt,name=category,proto3" json:"category,omitempty"`
	Level         string                 `protobuf:"bytes,6,opt,name=level,proto3" json:"level,omitempty"`
	ThumbnailUrl  string                 `protobuf:"bytes,7,opt,name=thumbnail_url,json=thumbnailUrl,proto3" json:"thumbnail_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Course) Reset() {
	*x = Course{}
	mi := &file_protos_course_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Course) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Course) ProtoMessage() {}

func (x *Course) ProtoReflect() protoreflect.Message {
	mi := &file_protos_course_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Course.ProtoReflect.Descriptor instead.
func (*Course) Descriptor() ([]byte, []int) {
	return file_protos_course_proto_rawDescGZIP(), []int{0}
}

func (x *Course) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Course) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Course) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Course) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Course) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *Course) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *Course) GetThumbnailUrl() string {
	if x != nil {
		return x.ThumbnailUrl
	}
	return ""
}

type Lesson struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CourseId      string                 `protobuf:"bytes,2,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	VideoUrl      string                 `protobuf:"bytes,4,opt,name=video_url,json=videoUrl,proto3" json:"video_url,omitempty"`
	Duration      string                 `protobuf:"bytes,5,opt,name=duration,proto3" json:"duration,omitempty"`
	OrderNumber   int32                  `protobuf:"varint,6,opt,name=order_number,json=orderNumber,proto3" json:"order_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Lesson) Reset() {
	*x = Lesson{}
	mi := &file_protos_course_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Lesson) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Lesson) ProtoMessage() {}

func (x *Lesson) ProtoReflect() protoreflect.Message {
	mi := &file_protos_course_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Lesson.ProtoReflect.Descriptor instead.
func (*Lesson) Descriptor() ([]byte, []int) {
	return file_protos_course_proto_rawDescGZIP(), []int{1}
}

func (x *Lesson) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Lesson) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

func (x *Lesson) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Lesson) GetVideoUrl() string {
	if x != nil {
		return x.VideoUrl
	}
	return ""
}

func (x *Lesson) GetDuration() string {
	if x != nil {
		return x.Duration
	}
	return ""
}

func (x *Lesson) GetOrderNumber() int32 {
	if x != nil {
		return x.OrderNumber
	}
	return 0
}

type CreateCourseReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Category      string                 `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	Level         string                 `protobuf:"bytes,5,opt,name=level,proto3" json:"level,omitempty"`
	ThumbnailUrl  string                 `protobuf:"bytes,6,opt,name=thumbnail_url,json=thumbnailUrl,proto3" json:"thumbnail_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCourseReq) Reset() {
	*x = CreateCourseReq{}
	mi := &file_protos_course_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCourseReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCourseReq) ProtoMessage() {}

func (x *CreateCourseReq) ProtoReflect() protoreflect.Message {
	mi := &file_protos_course_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCourseReq.ProtoReflect.Descriptor instead.
func (*CreateCourseReq) Descriptor() ([]byte, []int) {
	return file_protos_course_proto_rawDescGZIP(), []int{2}
}

func (x *CreateCourseReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateCourseReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateCourseReq) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateCourseReq) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *CreateCourseReq) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *CreateCourseReq) GetThumbnailUrl() string {
	if x != nil {
		return x.ThumbnailUrl
	}
	return ""
}

type CreateCourseResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        bool                   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCourseResp) Reset() {
	*x = CreateCourseResp{}
	mi := &file_protos_course_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCourseResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCourseResp) ProtoMessage() {}

func (x *CreateCourseResp) ProtoReflect() protoreflect.Message {
	mi := &file_protos_course_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCourseResp.ProtoReflect.Descriptor instead.
func (*CreateCourseResp) Descriptor() ([]byte, []int) {
	return file_protos_course_proto_rawDescGZIP(), []int{3}
}

func (x *CreateCourseResp) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *CreateCourseResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UpdateCourseReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Category      string                 `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	Level         string                 `protobuf:"bytes,5,opt,name=level,proto3" json:"level,omitempty"`
	ThumbnailUrl  string                 `protobuf:"bytes,6,opt,name=thumbnail_url,json=thumbnailUrl,proto3" json:"thumbnail_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCourseReq) Reset() {
	*x = UpdateCourseReq{}
	mi := &file_protos_course_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCourseReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCourseReq) ProtoMessage() {}

func (x *UpdateCourseReq) ProtoReflect() protoreflect.Message {
	mi := &file_protos_course_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCourseReq.ProtoReflect.Descriptor instead.
func (*UpdateCourseReq) Descriptor() ([]byte, []int) {
	return file_protos_course_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateCourseReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateCourseReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateCourseReq) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateCourseReq) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *UpdateCourseReq) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *UpdateCourseReq) GetThumbnailUrl() string {
	if x != nil {
		return x.ThumbnailUrl
	}
	return ""
}

type UpdateCourseResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        bool                   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCourseResp) Reset() {
	*x = UpdateCourseResp{}
	mi := &file_protos_course_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCourseResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCourseResp) ProtoMessage() {}

func (x *UpdateCourseResp) ProtoReflect() protoreflect.Message {
	mi := &file_protos_course_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCourseResp.ProtoReflect.Descriptor instead.
func (*UpdateCourseResp) Descriptor() ([]byte, []int) {
	return file_protos_course_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateCourseResp) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *UpdateCourseResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DeleteCourseReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCourseReq) Reset() {
	*x = DeleteCourseReq{}
	mi := &file_protos_course_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCourseReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCourseReq) ProtoMessage() {}

func (x *DeleteCourseReq) ProtoReflect() protoreflect.Message {
	mi := &file_protos_course_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCourseReq.ProtoReflect.Descriptor instead.
func (*DeleteCourseReq) Descriptor() ([]byte, []int) {
	return file_protos_course_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteCourseReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteCourseResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        bool                   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCourseResp) Reset() {
	*x = DeleteCourseResp{}
	mi := &file_protos_course_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCourseResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCourseResp) ProtoMessage() {}

func (x *DeleteCourseResp) ProtoReflect() protoreflect.Message {
	mi := &file_protos_course_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCourseResp.ProtoReflect.Descriptor instead.
func (*DeleteCourseResp) Descriptor() ([]byte, []int) {
	return file_protos_course_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteCourseResp) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *DeleteCourseResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetCoursesReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCoursesReq) Reset() {
	*x = GetCoursesReq{}
	mi := &file_protos_course_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCoursesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCoursesReq) ProtoMessage() {}

func (x *GetCoursesReq) ProtoReflect() protoreflect.Message {
	mi := &file_protos_course_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCoursesReq.ProtoReflect.Descriptor instead.
func (*GetCoursesReq) Descriptor() ([]byte, []int) {
	return file_protos_course_proto_rawDescGZIP(), []int{8}
}

type GetCoursesResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        bool                   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Courses       []*Course              `protobuf:"bytes,3,rep,name=courses,proto3" json:"courses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCoursesResp) Reset() {
	*x = GetCoursesResp{}
	mi := &file_protos_course_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCoursesResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCoursesResp) ProtoMessage() {}

func (x *GetCoursesResp) ProtoReflect() protoreflect.Message {
	mi := &file_protos_course_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCoursesResp.ProtoReflect.Descriptor instead.
func (*GetCoursesResp) Descriptor() ([]byte, []int) {
	return file_protos_course_proto_rawDescGZIP(), []int{9}
}

func (x *GetCoursesResp) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *GetCoursesResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetCoursesResp) GetCourses() []*Course {
	if x != nil {
		return x.Courses
	}
	return nil
}

type GetCourseByIdReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCourseByIdReq) Reset() {
	*x = GetCourseByIdReq{}
	mi := &file_protos_course_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCourseByIdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCourseByIdReq) ProtoMessage() {}

func (x *GetCourseByIdReq) ProtoReflect() protoreflect.Message {
	mi := &file_protos_course_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCourseByIdReq.ProtoReflect.Descriptor instead.
func (*GetCourseByIdReq) Descriptor() ([]byte, []int) {
	return file_protos_course_proto_rawDescGZIP(), []int{10}
}

func (x *GetCourseByIdReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetCourseByIdResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        bool                   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Course        *Course                `protobuf:"bytes,3,opt,name=course,proto3" json:"course,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCourseByIdResp) Reset() {
	*x = GetCourseByIdResp{}
	mi := &file_protos_course_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCourseByIdResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCourseByIdResp) ProtoMessage() {}

func (x *GetCourseByIdResp) ProtoReflect() protoreflect.Message {
	mi := &file_protos_course_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCourseByIdResp.ProtoReflect.Descriptor instead.
func (*GetCourseByIdResp) Descriptor() ([]byte, []int) {
	return file_protos_course_proto_rawDescGZIP(), []int{11}
}

func (x *GetCourseByIdResp) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *GetCourseByIdResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetCourseByIdResp) GetCourse() *Course {
	if x != nil {
		return x.Course
	}
	return nil
}

type GetCourseByUserIdReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCourseByUserIdReq) Reset() {
	*x = GetCourseByUserIdReq{}
	mi := &file_protos_course_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCourseByUserIdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCourseByUserIdReq) ProtoMessage() {}

func (x *GetCourseByUserIdReq) ProtoReflect() protoreflect.Message {
	mi := &file_protos_course_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCourseByUserIdReq.ProtoReflect.Descriptor instead.
func (*GetCourseByUserIdReq) Descriptor() ([]byte, []int) {
	return file_protos_course_proto_rawDescGZIP(), []int{12}
}

func (x *GetCourseByUserIdReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetCourseByUserIdResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        bool                   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Courses       []*Course              `protobuf:"bytes,3,rep,name=courses,proto3" json:"courses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCourseByUserIdResp) Reset() {
	*x = GetCourseByUserIdResp{}
	mi := &file_protos_course_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCourseByUserIdResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCourseByUserIdResp) ProtoMessage() {}

func (x *GetCourseByUserIdResp) ProtoReflect() protoreflect.Message {
	mi := &file_protos_course_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCourseByUserIdResp.ProtoReflect.Descriptor instead.
func (*GetCourseByUserIdResp) Descriptor() ([]byte, []int) {
	return file_protos_course_proto_rawDescGZIP(), []int{13}
}

func (x *GetCourseByUserIdResp) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *GetCourseByUserIdResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetCourseByUserIdResp) GetCourses() []*Course {
	if x != nil {
		return x.Courses
	}
	return nil
}

type CreateLessonReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CourseId      string                 `protobuf:"bytes,1,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	VideoUrl      string                 `protobuf:"bytes,3,opt,name=video_url,json=videoUrl,proto3" json:"video_url,omitempty"`
	Duration      string                 `protobuf:"bytes,4,opt,name=duration,proto3" json:"duration,omitempty"`
	OrderNumber   int32                  `protobuf:"varint,5,opt,name=order_number,json=orderNumber,proto3" json:"order_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateLessonReq) Reset() {
	*x = CreateLessonReq{}
	mi := &file_protos_course_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLessonReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLessonReq) ProtoMessage() {}

func (x *CreateLessonReq) ProtoReflect() protoreflect.Message {
	mi := &file_protos_course_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLessonReq.ProtoReflect.Descriptor instead.
func (*CreateLessonReq) Descriptor() ([]byte, []int) {
	return file_protos_course_proto_rawDescGZIP(), []int{14}
}

func (x *CreateLessonReq) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

func (x *CreateLessonReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateLessonReq) GetVideoUrl() string {
	if x != nil {
		return x.VideoUrl
	}
	return ""
}

func (x *CreateLessonReq) GetDuration() string {
	if x != nil {
		return x.Duration
	}
	return ""
}

func (x *CreateLessonReq) GetOrderNumber() int32 {
	if x != nil {
		return x.OrderNumber
	}
	return 0
}

type CreateLessonResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        bool                   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateLessonResp) Reset() {
	*x = CreateLessonResp{}
	mi := &file_protos_course_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLessonResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLessonResp) ProtoMessage() {}

func (x *CreateLessonResp) ProtoReflect() protoreflect.Message {
	mi := &file_protos_course_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLessonResp.ProtoReflect.Descriptor instead.
func (*CreateLessonResp) Descriptor() ([]byte, []int) {
	return file_protos_course_proto_rawDescGZIP(), []int{15}
}

func (x *CreateLessonResp) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *CreateLessonResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UpdateLessonReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	VideoUrl      string                 `protobuf:"bytes,3,opt,name=video_url,json=videoUrl,proto3" json:"video_url,omitempty"`
	Duration      string                 `protobuf:"bytes,4,opt,name=duration,proto3" json:"duration,omitempty"`
	OrderNumber   int32                  `protobuf:"varint,5,opt,name=order_number,json=orderNumber,proto3" json:"order_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateLessonReq) Reset() {
	*x = UpdateLessonReq{}
	mi := &file_protos_course_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateLessonReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLessonReq) ProtoMessage() {}

func (x *UpdateLessonReq) ProtoReflect() protoreflect.Message {
	mi := &file_protos_course_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLessonReq.ProtoReflect.Descriptor instead.
func (*UpdateLessonReq) Descriptor() ([]byte, []int) {
	return file_protos_course_proto_rawDescGZIP(), []int{16}
}

func (x *UpdateLessonReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateLessonReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateLessonReq) GetVideoUrl() string {
	if x != nil {
		return x.VideoUrl
	}
	return ""
}

func (x *UpdateLessonReq) GetDuration() string {
	if x != nil {
		return x.Duration
	}
	return ""
}

func (x *UpdateLessonReq) GetOrderNumber() int32 {
	if x != nil {
		return x.OrderNumber
	}
	return 0
}

type UpdateLessonResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        bool                   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateLessonResp) Reset() {
	*x = UpdateLessonResp{}
	mi := &file_protos_course_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateLessonResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLessonResp) ProtoMessage() {}

func (x *UpdateLessonResp) ProtoReflect() protoreflect.Message {
	mi := &file_protos_course_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLessonResp.ProtoReflect.Descriptor instead.
func (*UpdateLessonResp) Descriptor() ([]byte, []int) {
	return file_protos_course_proto_rawDescGZIP(), []int{17}
}

func (x *UpdateLessonResp) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *UpdateLessonResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DeleteLessonReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteLessonReq) Reset() {
	*x = DeleteLessonReq{}
	mi := &file_protos_course_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteLessonReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteLessonReq) ProtoMessage() {}

func (x *DeleteLessonReq) ProtoReflect() protoreflect.Message {
	mi := &file_protos_course_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteLessonReq.ProtoReflect.Descriptor instead.
func (*DeleteLessonReq) Descriptor() ([]byte, []int) {
	return file_protos_course_proto_rawDescGZIP(), []int{18}
}

func (x *DeleteLessonReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteLessonResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        bool                   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteLessonResp) Reset() {
	*x = DeleteLessonResp{}
	mi := &file_protos_course_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteLessonResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteLessonResp) ProtoMessage() {}

func (x *DeleteLessonResp) ProtoReflect() protoreflect.Message {
	mi := &file_protos_course_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteLessonResp.ProtoReflect.Descriptor instead.
func (*DeleteLessonResp) Descriptor() ([]byte, []int) {
	return file_protos_course_proto_rawDescGZIP(), []int{19}
}

func (x *DeleteLessonResp) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *DeleteLessonResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetLessonByIdReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLessonByIdReq) Reset() {
	*x = GetLessonByIdReq{}
	mi := &file_protos_course_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLessonByIdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLessonByIdReq) ProtoMessage() {}

func (x *GetLessonByIdReq) ProtoReflect() protoreflect.Message {
	mi := &file_protos_course_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLessonByIdReq.ProtoReflect.Descriptor instead.
func (*GetLessonByIdReq) Descriptor() ([]byte, []int) {
	return file_protos_course_proto_rawDescGZIP(), []int{20}
}

func (x *GetLessonByIdReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetLessonByIdResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        bool                   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLessonByIdResp) Reset() {
	*x = GetLessonByIdResp{}
	mi := &file_protos_course_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLessonByIdResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLessonByIdResp) ProtoMessage() {}

func (x *GetLessonByIdResp) ProtoReflect() protoreflect.Message {
	mi := &file_protos_course_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLessonByIdResp.ProtoReflect.Descriptor instead.
func (*GetLessonByIdResp) Descriptor() ([]byte, []int) {
	return file_protos_course_proto_rawDescGZIP(), []int{21}
}

func (x *GetLessonByIdResp) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *GetLessonByIdResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetLessonsByCourseIdReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CourseId      string                 `protobuf:"bytes,1,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLessonsByCourseIdReq) Reset() {
	*x = GetLessonsByCourseIdReq{}
	mi := &file_protos_course_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLessonsByCourseIdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLessonsByCourseIdReq) ProtoMessage() {}

func (x *GetLessonsByCourseIdReq) ProtoReflect() protoreflect.Message {
	mi := &file_protos_course_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLessonsByCourseIdReq.ProtoReflect.Descriptor instead.
func (*GetLessonsByCourseIdReq) Descriptor() ([]byte, []int) {
	return file_protos_course_proto_rawDescGZIP(), []int{22}
}

func (x *GetLessonsByCourseIdReq) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

type GetLessonsByCourseIdResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        bool                   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Lessons       []*Lesson              `protobuf:"bytes,3,rep,name=lessons,proto3" json:"lessons,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLessonsByCourseIdResp) Reset() {
	*x = GetLessonsByCourseIdResp{}
	mi := &file_protos_course_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLessonsByCourseIdResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLessonsByCourseIdResp) ProtoMessage() {}

func (x *GetLessonsByCourseIdResp) ProtoReflect() protoreflect.Message {
	mi := &file_protos_course_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLessonsByCourseIdResp.ProtoReflect.Descriptor instead.
func (*GetLessonsByCourseIdResp) Descriptor() ([]byte, []int) {
	return file_protos_course_proto_rawDescGZIP(), []int{23}
}

func (x *GetLessonsByCourseIdResp) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *GetLessonsByCourseIdResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetLessonsByCourseIdResp) GetLessons() []*Lesson {
	if x != nil {
		return x.Lessons
	}
	return nil
}

var File_protos_course_proto protoreflect.FileDescriptor

const file_protos_course_proto_rawDesc = "" +
	"\n" +
	"\x13protos/course.proto\"\xc0\x01\n" +
	"\x06Course\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1a\n" +
	"\bcategory\x18\x05 \x01(\tR\bcategory\x12\x14\n" +
	"\x05level\x18\x06 \x01(\tR\x05level\x12#\n" +
	"\rthumbnail_url\x18\a \x01(\tR\fthumbnailUrl\"\xa7\x01\n" +
	"\x06Lesson\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tcourse_id\x18\x02 \x01(\tR\bcourseId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x1b\n" +
	"\tvideo_url\x18\x04 \x01(\tR\bvideoUrl\x12\x1a\n" +
	"\bduration\x18\x05 \x01(\tR\bduration\x12!\n" +
	"\forder_number\x18\x06 \x01(\x05R\vorderNumber\"\xb9\x01\n" +
	"\x0fCreateCourseReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1a\n" +
	"\bcategory\x18\x04 \x01(\tR\bcategory\x12\x14\n" +
	"\x05level\x18\x05 \x01(\tR\x05level\x12#\n" +
	"\rthumbnail_url\x18\x06 \x01(\tR\fthumbnailUrl\"D\n" +
	"\x10CreateCourseResp\x12\x16\n" +
	"\x06status\x18\x01 \x01(\bR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xb0\x01\n" +
	"\x0fUpdateCourseReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1a\n" +
	"\bcategory\x18\x04 \x01(\tR\bcategory\x12\x14\n" +
	"\x05level\x18\x05 \x01(\tR\x05level\x12#\n" +
	"\rthumbnail_url\x18\x06 \x01(\tR\fthumbnailUrl\"D\n" +
	"\x10UpdateCourseResp\x12\x16\n" +
	"\x06status\x18\x01 \x01(\bR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"!\n" +
	"\x0fDeleteCourseReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"D\n" +
	"\x10DeleteCourseResp\x12\x16\n" +
	"\x06status\x18\x01 \x01(\bR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x0f\n" +
	"\rGetCoursesReq\"e\n" +
	"\x0eGetCoursesResp\x12\x16\n" +
	"\x06status\x18\x01 \x01(\bR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12!\n" +
	"\acourses\x18\x03 \x03(\v2\a.CourseR\acourses\"\"\n" +
	"\x10GetCourseByIdReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"f\n" +
	"\x11GetCourseByIdResp\x12\x16\n" +
	"\x06status\x18\x01 \x01(\bR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1f\n" +
	"\x06course\x18\x03 \x01(\v2\a.CourseR\x06course\"/\n" +
	"\x14GetCourseByUserIdReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"l\n" +
	"\x15GetCourseByUserIdResp\x12\x16\n" +
	"\x06status\x18\x01 \x01(\bR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12!\n" +
	"\acourses\x18\x03 \x03(\v2\a.CourseR\acourses\"\xa0\x01\n" +
	"\x0fCreateLessonReq\x12\x1b\n" +
	"\tcourse_id\x18\x01 \x01(\tR\bcourseId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1b\n" +
	"\tvideo_url\x18\x03 \x01(\tR\bvideoUrl\x12\x1a\n" +
	"\bduration\x18\x04 \x01(\tR\bduration\x12!\n" +
	"\forder_number\x18\x05 \x01(\x05R\vorderNumber\"D\n" +
	"\x10CreateLessonResp\x12\x16\n" +
	"\x06status\x18\x01 \x01(\bR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x93\x01\n" +
	"\x0fUpdateLessonReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1b\n" +
	"\tvideo_url\x18\x03 \x01(\tR\bvideoUrl\x12\x1a\n" +
	"\bduration\x18\x04 \x01(\tR\bduration\x12!\n" +
	"\forder_number\x18\x05 \x01(\x05R\vorderNumber\"D\n" +
	"\x10UpdateLessonResp\x12\x16\n" +
	"\x06status\x18\x01 \x01(\bR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"!\n" +
	"\x0fDeleteLessonReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"D\n" +
	"\x10DeleteLessonResp\x12\x16\n" +
	"\x06status\x18\x01 \x01(\bR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\"\n" +
	"\x10GetLessonByIdReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"E\n" +
	"\x11GetLessonByIdResp\x12\x16\n" +
	"\x06status\x18\x01 \x01(\bR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"6\n" +
	"\x17GetLessonsByCourseIdReq\x12\x1b\n" +
	"\tcourse_id\x18\x01 \x01(\tR\bcourseId\"o\n" +
	"\x18GetLessonsByCourseIdResp\x12\x16\n" +
	"\x06status\x18\x01 \x01(\bR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12!\n" +
	"\alessons\x18\x03 \x03(\v2\a.LessonR\alessons2\xfd\x04\n" +
	"\rCourseService\x123\n" +
	"\fCreateCourse\x12\x10.CreateCourseReq\x1a\x11.CreateCourseResp\x123\n" +
	"\fUpdateCourse\x12\x10.UpdateCourseReq\x1a\x11.UpdateCourseResp\x123\n" +
	"\fDeleteCourse\x12\x10.DeleteCourseReq\x1a\x11.DeleteCourseResp\x126\n" +
	"\rGetCourseById\x12\x11.GetCourseByIdReq\x1a\x12.GetCourseByIdResp\x12-\n" +
	"\n" +
	"GetCourses\x12\x0e.GetCoursesReq\x1a\x0f.GetCoursesResp\x12B\n" +
	"\x11GetCourseByUserId\x12\x15.GetCourseByUserIdReq\x1a\x16.GetCourseByUserIdResp\x123\n" +
	"\fCreateLesson\x12\x10.CreateLessonReq\x1a\x11.CreateLessonResp\x123\n" +
	"\fUpdateLesson\x12\x10.UpdateLessonReq\x1a\x11.UpdateLessonResp\x123\n" +
	"\fDeleteLesson\x12\x10.DeleteLessonReq\x1a\x11.DeleteLessonResp\x126\n" +
	"\rGetLessonById\x12\x11.GetLessonByIdReq\x1a\x12.GetLessonByIdResp\x12K\n" +
	"\x14GetLessonsByCourseId\x12\x18.GetLessonsByCourseIdReq\x1a\x19.GetLessonsByCourseIdRespB\x13Z\x11genproto/coursepbb\x06proto3"

var (
	file_protos_course_proto_rawDescOnce sync.Once
	file_protos_course_proto_rawDescData []byte
)

func file_protos_course_proto_rawDescGZIP() []byte {
	file_protos_course_proto_rawDescOnce.Do(func() {
		file_protos_course_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_course_proto_rawDesc), len(file_protos_course_proto_rawDesc)))
	})
	return file_protos_course_proto_rawDescData
}

var file_protos_course_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_protos_course_proto_goTypes = []any{
	(*Course)(nil),                   // 0: Course
	(*Lesson)(nil),                   // 1: Lesson
	(*CreateCourseReq)(nil),          // 2: CreateCourseReq
	(*CreateCourseResp)(nil),         // 3: CreateCourseResp
	(*UpdateCourseReq)(nil),          // 4: UpdateCourseReq
	(*UpdateCourseResp)(nil),         // 5: UpdateCourseResp
	(*DeleteCourseReq)(nil),          // 6: DeleteCourseReq
	(*DeleteCourseResp)(nil),         // 7: DeleteCourseResp
	(*GetCoursesReq)(nil),            // 8: GetCoursesReq
	(*GetCoursesResp)(nil),           // 9: GetCoursesResp
	(*GetCourseByIdReq)(nil),         // 10: GetCourseByIdReq
	(*GetCourseByIdResp)(nil),        // 11: GetCourseByIdResp
	(*GetCourseByUserIdReq)(nil),     // 12: GetCourseByUserIdReq
	(*GetCourseByUserIdResp)(nil),    // 13: GetCourseByUserIdResp
	(*CreateLessonReq)(nil),          // 14: CreateLessonReq
	(*CreateLessonResp)(nil),         // 15: CreateLessonResp
	(*UpdateLessonReq)(nil),          // 16: UpdateLessonReq
	(*UpdateLessonResp)(nil),         // 17: UpdateLessonResp
	(*DeleteLessonReq)(nil),          // 18: DeleteLessonReq
	(*DeleteLessonResp)(nil),         // 19: DeleteLessonResp
	(*GetLessonByIdReq)(nil),         // 20: GetLessonByIdReq
	(*GetLessonByIdResp)(nil),        // 21: GetLessonByIdResp
	(*GetLessonsByCourseIdReq)(nil),  // 22: GetLessonsByCourseIdReq
	(*GetLessonsByCourseIdResp)(nil), // 23: GetLessonsByCourseIdResp
}
var file_protos_course_proto_depIdxs = []int32{
	0,  // 0: GetCoursesResp.courses:type_name -> Course
	0,  // 1: GetCourseByIdResp.course:type_name -> Course
	0,  // 2: GetCourseByUserIdResp.courses:type_name -> Course
	1,  // 3: GetLessonsByCourseIdResp.lessons:type_name -> Lesson
	2,  // 4: CourseService.CreateCourse:input_type -> CreateCourseReq
	4,  // 5: CourseService.UpdateCourse:input_type -> UpdateCourseReq
	6,  // 6: CourseService.DeleteCourse:input_type -> DeleteCourseReq
	10, // 7: CourseService.GetCourseById:input_type -> GetCourseByIdReq
	8,  // 8: CourseService.GetCourses:input_type -> GetCoursesReq
	12, // 9: CourseService.GetCourseByUserId:input_type -> GetCourseByUserIdReq
	14, // 10: CourseService.CreateLesson:input_type -> CreateLessonReq
	16, // 11: CourseService.UpdateLesson:input_type -> UpdateLessonReq
	18, // 12: CourseService.DeleteLesson:input_type -> DeleteLessonReq
	20, // 13: CourseService.GetLessonById:input_type -> GetLessonByIdReq
	22, // 14: CourseService.GetLessonsByCourseId:input_type -> GetLessonsByCourseIdReq
	3,  // 15: CourseService.CreateCourse:output_type -> CreateCourseResp
	5,  // 16: CourseService.UpdateCourse:output_type -> UpdateCourseResp
	7,  // 17: CourseService.DeleteCourse:output_type -> DeleteCourseResp
	11, // 18: CourseService.GetCourseById:output_type -> GetCourseByIdResp
	9,  // 19: CourseService.GetCourses:output_type -> GetCoursesResp
	13, // 20: CourseService.GetCourseByUserId:output_type -> GetCourseByUserIdResp
	15, // 21: CourseService.CreateLesson:output_type -> CreateLessonResp
	17, // 22: CourseService.UpdateLesson:output_type -> UpdateLessonResp
	19, // 23: CourseService.DeleteLesson:output_type -> DeleteLessonResp
	21, // 24: CourseService.GetLessonById:output_type -> GetLessonByIdResp
	23, // 25: CourseService.GetLessonsByCourseId:output_type -> GetLessonsByCourseIdResp
	15, // [15:26] is the sub-list for method output_type
	4,  // [4:15] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_protos_course_proto_init() }
func file_protos_course_proto_init() {
	if File_protos_course_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_course_proto_rawDesc), len(file_protos_course_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_course_proto_goTypes,
		DependencyIndexes: file_protos_course_proto_depIdxs,
		MessageInfos:      file_protos_course_proto_msgTypes,
	}.Build()
	File_protos_course_proto = out.File
	file_protos_course_proto_goTypes = nil
	file_protos_course_proto_depIdxs = nil
}
