
apigateway:
  host: localhost
  port: 9090

authservice:
  host: localhost
  port: 9001

postservice:
  host: localhost
  port: 9002

commentservice:
  host: localhost
  port: 9003
  
likeservice:
  host: localhost
  port: 9004

courseservice:
  host: localhost
  port: 9005
