// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package storage

import (
	"database/sql"
)

type Course struct {
	ID           int32
	UserID       int32
	Title        string
	Description  string
	Category     string
	Level        string
	ThumbnailUrl string
	CreatedAt    sql.NullTime
	UpdatedAt    sql.NullTime
	DeletedAt    sql.NullInt32
}

type Lesson struct {
	ID          int32
	CourseID    sql.NullInt32
	Title       string
	VideoUrl    string
	Duration    int32
	OrderNumber int32
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
	DeletedAt   sql.NullInt32
}
