// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package storage

import (
	"context"
	"database/sql"
)

const createCourse = `-- name: CreateCourse :exec
INSERT INTO courses
(
    user_id,
    title,
    description,
    category,
    level,
    thumbnail_url
) VALUES (
    $1, $2, $3, $4, $5, $6
)
`

type CreateCourseParams struct {
	UserID       int32
	Title        string
	Description  string
	Category     string
	Level        string
	ThumbnailUrl string
}

func (q *Queries) CreateCourse(ctx context.Context, arg CreateCourseParams) error {
	_, err := q.db.ExecContext(ctx, createCourse,
		arg.UserID,
		arg.Title,
		arg.Description,
		arg.Category,
		arg.Level,
		arg.ThumbnailUrl,
	)
	return err
}

const createLesson = `-- name: CreateLesson :exec
INSERT INTO lessons(
    course_id,
    title,
    video_url,
    duration,
    order_number
) VALUES (
    $1, $2, $3, $4, $5
)
`

type CreateLessonParams struct {
	CourseID    sql.NullInt32
	Title       string
	VideoUrl    string
	Duration    int32
	OrderNumber int32
}

func (q *Queries) CreateLesson(ctx context.Context, arg CreateLessonParams) error {
	_, err := q.db.ExecContext(ctx, createLesson,
		arg.CourseID,
		arg.Title,
		arg.VideoUrl,
		arg.Duration,
		arg.OrderNumber,
	)
	return err
}

const deleteCourse = `-- name: DeleteCourse :exec
UPDATE courses
SET deleted_at = EXTRACT(EPOCH FROM NOW())
WHERE id = $1
`

func (q *Queries) DeleteCourse(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteCourse, id)
	return err
}

const deleteLesson = `-- name: DeleteLesson :exec
UPDATE lessons
SET
    deleted_at = EXTRACT(EPOCH FROM NOW())
WHERE id = $1
`

func (q *Queries) DeleteLesson(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteLesson, id)
	return err
}

const getCourseById = `-- name: GetCourseById :one
SELECT
    id,
    user_id,
    title,
    description,
    category,
    level,
    thumbnail_url
FROM courses WHERE id = $1 and deleted_at = 0
`

type GetCourseByIdRow struct {
	ID           int32
	UserID       int32
	Title        string
	Description  string
	Category     string
	Level        string
	ThumbnailUrl string
}

func (q *Queries) GetCourseById(ctx context.Context, id int32) (GetCourseByIdRow, error) {
	row := q.db.QueryRowContext(ctx, getCourseById, id)
	var i GetCourseByIdRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Category,
		&i.Level,
		&i.ThumbnailUrl,
	)
	return i, err
}

const getCourseByUserId = `-- name: GetCourseByUserId :many
SELECT
    id,
    user_id,
    title,
    description,
    category,
    level,
    thumbnail_url
FROM courses WHERE user_id = $1 and deleted_at = 0
`

type GetCourseByUserIdRow struct {
	ID           int32
	UserID       int32
	Title        string
	Description  string
	Category     string
	Level        string
	ThumbnailUrl string
}

func (q *Queries) GetCourseByUserId(ctx context.Context, userID int32) ([]GetCourseByUserIdRow, error) {
	rows, err := q.db.QueryContext(ctx, getCourseByUserId, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCourseByUserIdRow
	for rows.Next() {
		var i GetCourseByUserIdRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Description,
			&i.Category,
			&i.Level,
			&i.ThumbnailUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCourses = `-- name: GetCourses :many
SELECT
    id,
    user_id,
    title,
    description,
    category,
    level,
    thumbnail_url
FROM courses WHERE deleted_at = 0
`

type GetCoursesRow struct {
	ID           int32
	UserID       int32
	Title        string
	Description  string
	Category     string
	Level        string
	ThumbnailUrl string
}

func (q *Queries) GetCourses(ctx context.Context) ([]GetCoursesRow, error) {
	rows, err := q.db.QueryContext(ctx, getCourses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCoursesRow
	for rows.Next() {
		var i GetCoursesRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Description,
			&i.Category,
			&i.Level,
			&i.ThumbnailUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLessonByCourseId = `-- name: GetLessonByCourseId :many
SELECT
    id,
    course_id,
    title,
    video_url,
    duration,
    order_number
FROM lessons
WHERE course_id = $1 AND deleted_at = 0
`

type GetLessonByCourseIdRow struct {
	ID          int32
	CourseID    sql.NullInt32
	Title       string
	VideoUrl    string
	Duration    int32
	OrderNumber int32
}

func (q *Queries) GetLessonByCourseId(ctx context.Context, courseID sql.NullInt32) ([]GetLessonByCourseIdRow, error) {
	rows, err := q.db.QueryContext(ctx, getLessonByCourseId, courseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetLessonByCourseIdRow
	for rows.Next() {
		var i GetLessonByCourseIdRow
		if err := rows.Scan(
			&i.ID,
			&i.CourseID,
			&i.Title,
			&i.VideoUrl,
			&i.Duration,
			&i.OrderNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLessonById = `-- name: GetLessonById :one
SELECT
    id,
    course_id,
    title,
    video_url,
    duration,
    order_number
FROM lessons
WHERE id = $1 AND deleted_at = 0
`

type GetLessonByIdRow struct {
	ID          int32
	CourseID    sql.NullInt32
	Title       string
	VideoUrl    string
	Duration    int32
	OrderNumber int32
}

func (q *Queries) GetLessonById(ctx context.Context, id int32) (GetLessonByIdRow, error) {
	row := q.db.QueryRowContext(ctx, getLessonById, id)
	var i GetLessonByIdRow
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.Title,
		&i.VideoUrl,
		&i.Duration,
		&i.OrderNumber,
	)
	return i, err
}

const updateCourse = `-- name: UpdateCourse :exec
UPDATE courses
SET
    title = $2,
    description = $3,
    category = $4,
    level = $5,
    thumbnail_url = $6
WHERE id = $1 and deleted_at = 0
`

type UpdateCourseParams struct {
	ID           int32
	Title        string
	Description  string
	Category     string
	Level        string
	ThumbnailUrl string
}

func (q *Queries) UpdateCourse(ctx context.Context, arg UpdateCourseParams) error {
	_, err := q.db.ExecContext(ctx, updateCourse,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Category,
		arg.Level,
		arg.ThumbnailUrl,
	)
	return err
}

const updateLesson = `-- name: UpdateLesson :exec
UPDATE lessons
SET 
    title = $2,
    video_url = $3,
    duration = $4,
    order_number = $5
WHERE id = $1 AND deleted_at = 0
`

type UpdateLessonParams struct {
	ID          int32
	Title       string
	VideoUrl    string
	Duration    int32
	OrderNumber int32
}

func (q *Queries) UpdateLesson(ctx context.Context, arg UpdateLessonParams) error {
	_, err := q.db.ExecContext(ctx, updateLesson,
		arg.ID,
		arg.Title,
		arg.VideoUrl,
		arg.Duration,
		arg.OrderNumber,
	)
	return err
}
