// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.12
// source: protos/post.proto

package postpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Post struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Post) Reset() {
	*x = Post{}
	mi := &file_protos_post_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Post) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Post) ProtoMessage() {}

func (x *Post) ProtoReflect() protoreflect.Message {
	mi := &file_protos_post_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Post.ProtoReflect.Descriptor instead.
func (*Post) Descriptor() ([]byte, []int) {
	return file_protos_post_proto_rawDescGZIP(), []int{0}
}

func (x *Post) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Post) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Post) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type CreatePostReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePostReq) Reset() {
	*x = CreatePostReq{}
	mi := &file_protos_post_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePostReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePostReq) ProtoMessage() {}

func (x *CreatePostReq) ProtoReflect() protoreflect.Message {
	mi := &file_protos_post_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePostReq.ProtoReflect.Descriptor instead.
func (*CreatePostReq) Descriptor() ([]byte, []int) {
	return file_protos_post_proto_rawDescGZIP(), []int{1}
}

func (x *CreatePostReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreatePostReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type CreatePostResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        bool                   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePostResp) Reset() {
	*x = CreatePostResp{}
	mi := &file_protos_post_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePostResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePostResp) ProtoMessage() {}

func (x *CreatePostResp) ProtoReflect() protoreflect.Message {
	mi := &file_protos_post_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePostResp.ProtoReflect.Descriptor instead.
func (*CreatePostResp) Descriptor() ([]byte, []int) {
	return file_protos_post_proto_rawDescGZIP(), []int{2}
}

func (x *CreatePostResp) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *CreatePostResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UpdatePostReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePostReq) Reset() {
	*x = UpdatePostReq{}
	mi := &file_protos_post_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePostReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePostReq) ProtoMessage() {}

func (x *UpdatePostReq) ProtoReflect() protoreflect.Message {
	mi := &file_protos_post_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePostReq.ProtoReflect.Descriptor instead.
func (*UpdatePostReq) Descriptor() ([]byte, []int) {
	return file_protos_post_proto_rawDescGZIP(), []int{3}
}

func (x *UpdatePostReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdatePostReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type UpdatePostResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        bool                   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePostResp) Reset() {
	*x = UpdatePostResp{}
	mi := &file_protos_post_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePostResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePostResp) ProtoMessage() {}

func (x *UpdatePostResp) ProtoReflect() protoreflect.Message {
	mi := &file_protos_post_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePostResp.ProtoReflect.Descriptor instead.
func (*UpdatePostResp) Descriptor() ([]byte, []int) {
	return file_protos_post_proto_rawDescGZIP(), []int{4}
}

func (x *UpdatePostResp) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *UpdatePostResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DeletePostReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePostReq) Reset() {
	*x = DeletePostReq{}
	mi := &file_protos_post_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePostReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePostReq) ProtoMessage() {}

func (x *DeletePostReq) ProtoReflect() protoreflect.Message {
	mi := &file_protos_post_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePostReq.ProtoReflect.Descriptor instead.
func (*DeletePostReq) Descriptor() ([]byte, []int) {
	return file_protos_post_proto_rawDescGZIP(), []int{5}
}

func (x *DeletePostReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeletePostResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        bool                   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePostResp) Reset() {
	*x = DeletePostResp{}
	mi := &file_protos_post_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePostResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePostResp) ProtoMessage() {}

func (x *DeletePostResp) ProtoReflect() protoreflect.Message {
	mi := &file_protos_post_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePostResp.ProtoReflect.Descriptor instead.
func (*DeletePostResp) Descriptor() ([]byte, []int) {
	return file_protos_post_proto_rawDescGZIP(), []int{6}
}

func (x *DeletePostResp) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *DeletePostResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetPostByIdReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPostByIdReq) Reset() {
	*x = GetPostByIdReq{}
	mi := &file_protos_post_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPostByIdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPostByIdReq) ProtoMessage() {}

func (x *GetPostByIdReq) ProtoReflect() protoreflect.Message {
	mi := &file_protos_post_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPostByIdReq.ProtoReflect.Descriptor instead.
func (*GetPostByIdReq) Descriptor() ([]byte, []int) {
	return file_protos_post_proto_rawDescGZIP(), []int{7}
}

func (x *GetPostByIdReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetPostByIdResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        bool                   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Post          *Post                  `protobuf:"bytes,3,opt,name=post,proto3" json:"post,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPostByIdResp) Reset() {
	*x = GetPostByIdResp{}
	mi := &file_protos_post_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPostByIdResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPostByIdResp) ProtoMessage() {}

func (x *GetPostByIdResp) ProtoReflect() protoreflect.Message {
	mi := &file_protos_post_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPostByIdResp.ProtoReflect.Descriptor instead.
func (*GetPostByIdResp) Descriptor() ([]byte, []int) {
	return file_protos_post_proto_rawDescGZIP(), []int{8}
}

func (x *GetPostByIdResp) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *GetPostByIdResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetPostByIdResp) GetPost() *Post {
	if x != nil {
		return x.Post
	}
	return nil
}

type GetAllPostsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllPostsReq) Reset() {
	*x = GetAllPostsReq{}
	mi := &file_protos_post_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllPostsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllPostsReq) ProtoMessage() {}

func (x *GetAllPostsReq) ProtoReflect() protoreflect.Message {
	mi := &file_protos_post_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllPostsReq.ProtoReflect.Descriptor instead.
func (*GetAllPostsReq) Descriptor() ([]byte, []int) {
	return file_protos_post_proto_rawDescGZIP(), []int{9}
}

type GetAllPostsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        bool                   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Posts         []*Post                `protobuf:"bytes,3,rep,name=posts,proto3" json:"posts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllPostsResp) Reset() {
	*x = GetAllPostsResp{}
	mi := &file_protos_post_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllPostsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllPostsResp) ProtoMessage() {}

func (x *GetAllPostsResp) ProtoReflect() protoreflect.Message {
	mi := &file_protos_post_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllPostsResp.ProtoReflect.Descriptor instead.
func (*GetAllPostsResp) Descriptor() ([]byte, []int) {
	return file_protos_post_proto_rawDescGZIP(), []int{10}
}

func (x *GetAllPostsResp) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *GetAllPostsResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetAllPostsResp) GetPosts() []*Post {
	if x != nil {
		return x.Posts
	}
	return nil
}

type GetAllPostsByUserIdReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllPostsByUserIdReq) Reset() {
	*x = GetAllPostsByUserIdReq{}
	mi := &file_protos_post_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllPostsByUserIdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllPostsByUserIdReq) ProtoMessage() {}

func (x *GetAllPostsByUserIdReq) ProtoReflect() protoreflect.Message {
	mi := &file_protos_post_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllPostsByUserIdReq.ProtoReflect.Descriptor instead.
func (*GetAllPostsByUserIdReq) Descriptor() ([]byte, []int) {
	return file_protos_post_proto_rawDescGZIP(), []int{11}
}

func (x *GetAllPostsByUserIdReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetAllPostsByUserIdResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        bool                   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Posts         []*Post                `protobuf:"bytes,3,rep,name=posts,proto3" json:"posts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllPostsByUserIdResp) Reset() {
	*x = GetAllPostsByUserIdResp{}
	mi := &file_protos_post_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllPostsByUserIdResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllPostsByUserIdResp) ProtoMessage() {}

func (x *GetAllPostsByUserIdResp) ProtoReflect() protoreflect.Message {
	mi := &file_protos_post_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllPostsByUserIdResp.ProtoReflect.Descriptor instead.
func (*GetAllPostsByUserIdResp) Descriptor() ([]byte, []int) {
	return file_protos_post_proto_rawDescGZIP(), []int{12}
}

func (x *GetAllPostsByUserIdResp) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *GetAllPostsByUserIdResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetAllPostsByUserIdResp) GetPosts() []*Post {
	if x != nil {
		return x.Posts
	}
	return nil
}

var File_protos_post_proto protoreflect.FileDescriptor

const file_protos_post_proto_rawDesc = "" +
	"\n" +
	"\x11protos/post.proto\"I\n" +
	"\x04Post\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\"B\n" +
	"\rCreatePostReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"B\n" +
	"\x0eCreatePostResp\x12\x16\n" +
	"\x06status\x18\x01 \x01(\bR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"9\n" +
	"\rUpdatePostReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"B\n" +
	"\x0eUpdatePostResp\x12\x16\n" +
	"\x06status\x18\x01 \x01(\bR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x1f\n" +
	"\rDeletePostReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"B\n" +
	"\x0eDeletePostResp\x12\x16\n" +
	"\x06status\x18\x01 \x01(\bR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\" \n" +
	"\x0eGetPostByIdReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"^\n" +
	"\x0fGetPostByIdResp\x12\x16\n" +
	"\x06status\x18\x01 \x01(\bR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x19\n" +
	"\x04post\x18\x03 \x01(\v2\x05.PostR\x04post\"\x10\n" +
	"\x0eGetAllPostsReq\"`\n" +
	"\x0fGetAllPostsResp\x12\x16\n" +
	"\x06status\x18\x01 \x01(\bR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1b\n" +
	"\x05posts\x18\x03 \x03(\v2\x05.PostR\x05posts\"1\n" +
	"\x16GetAllPostsByUserIdReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"h\n" +
	"\x17GetAllPostsByUserIdResp\x12\x16\n" +
	"\x06status\x18\x01 \x01(\bR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1b\n" +
	"\x05posts\x18\x03 \x03(\v2\x05.PostR\x05posts2\xc8\x02\n" +
	"\vPostService\x12-\n" +
	"\n" +
	"CreatePost\x12\x0e.CreatePostReq\x1a\x0f.CreatePostResp\x12-\n" +
	"\n" +
	"UpdatePost\x12\x0e.UpdatePostReq\x1a\x0f.UpdatePostResp\x12-\n" +
	"\n" +
	"DeletePost\x12\x0e.DeletePostReq\x1a\x0f.DeletePostResp\x120\n" +
	"\vGetPostById\x12\x0f.GetPostByIdReq\x1a\x10.GetPostByIdResp\x120\n" +
	"\vGetAllPosts\x12\x0f.GetAllPostsReq\x1a\x10.GetAllPostsResp\x12H\n" +
	"\x13GetAllPostsByUserId\x12\x17.GetAllPostsByUserIdReq\x1a\x18.GetAllPostsByUserIdRespB\x11Z\x0fgenproto/postpbb\x06proto3"

var (
	file_protos_post_proto_rawDescOnce sync.Once
	file_protos_post_proto_rawDescData []byte
)

func file_protos_post_proto_rawDescGZIP() []byte {
	file_protos_post_proto_rawDescOnce.Do(func() {
		file_protos_post_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_post_proto_rawDesc), len(file_protos_post_proto_rawDesc)))
	})
	return file_protos_post_proto_rawDescData
}

var file_protos_post_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_protos_post_proto_goTypes = []any{
	(*Post)(nil),                    // 0: Post
	(*CreatePostReq)(nil),           // 1: CreatePostReq
	(*CreatePostResp)(nil),          // 2: CreatePostResp
	(*UpdatePostReq)(nil),           // 3: UpdatePostReq
	(*UpdatePostResp)(nil),          // 4: UpdatePostResp
	(*DeletePostReq)(nil),           // 5: DeletePostReq
	(*DeletePostResp)(nil),          // 6: DeletePostResp
	(*GetPostByIdReq)(nil),          // 7: GetPostByIdReq
	(*GetPostByIdResp)(nil),         // 8: GetPostByIdResp
	(*GetAllPostsReq)(nil),          // 9: GetAllPostsReq
	(*GetAllPostsResp)(nil),         // 10: GetAllPostsResp
	(*GetAllPostsByUserIdReq)(nil),  // 11: GetAllPostsByUserIdReq
	(*GetAllPostsByUserIdResp)(nil), // 12: GetAllPostsByUserIdResp
}
var file_protos_post_proto_depIdxs = []int32{
	0,  // 0: GetPostByIdResp.post:type_name -> Post
	0,  // 1: GetAllPostsResp.posts:type_name -> Post
	0,  // 2: GetAllPostsByUserIdResp.posts:type_name -> Post
	1,  // 3: PostService.CreatePost:input_type -> CreatePostReq
	3,  // 4: PostService.UpdatePost:input_type -> UpdatePostReq
	5,  // 5: PostService.DeletePost:input_type -> DeletePostReq
	7,  // 6: PostService.GetPostById:input_type -> GetPostByIdReq
	9,  // 7: PostService.GetAllPosts:input_type -> GetAllPostsReq
	11, // 8: PostService.GetAllPostsByUserId:input_type -> GetAllPostsByUserIdReq
	2,  // 9: PostService.CreatePost:output_type -> CreatePostResp
	4,  // 10: PostService.UpdatePost:output_type -> UpdatePostResp
	6,  // 11: PostService.DeletePost:output_type -> DeletePostResp
	8,  // 12: PostService.GetPostById:output_type -> GetPostByIdResp
	10, // 13: PostService.GetAllPosts:output_type -> GetAllPostsResp
	12, // 14: PostService.GetAllPostsByUserId:output_type -> GetAllPostsByUserIdResp
	9,  // [9:15] is the sub-list for method output_type
	3,  // [3:9] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_protos_post_proto_init() }
func file_protos_post_proto_init() {
	if File_protos_post_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_post_proto_rawDesc), len(file_protos_post_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_post_proto_goTypes,
		DependencyIndexes: file_protos_post_proto_depIdxs,
		MessageInfos:      file_protos_post_proto_msgTypes,
	}.Build()
	File_protos_post_proto = out.File
	file_protos_post_proto_goTypes = nil
	file_protos_post_proto_depIdxs = nil
}
