// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package storage

import (
	"context"
)

const createPost = `-- name: CreatePost :exec
INSERT INTO posts
(
    user_id,
    content
) VALUES (
    $1, $2
)
`

type CreatePostParams struct {
	UserID  int32
	Content string
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) error {
	_, err := q.db.ExecContext(ctx, createPost, arg.UserID, arg.Content)
	return err
}

const deletePost = `-- name: DeletePost :exec
UPDATE posts
SET deleted_at = EXTRACT(EPOCH FROM NOW())
WHERE id = $1 AND deleted_at = 0
`

func (q *Queries) DeletePost(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deletePost, id)
	return err
}

const getAllPosts = `-- name: GetAllPosts :many
SELECT
    id,
    user_id,
    content
FROM posts
WHERE deleted_at = 0
`

type GetAllPostsRow struct {
	ID      int32
	UserID  int32
	Content string
}

func (q *Queries) GetAllPosts(ctx context.Context) ([]GetAllPostsRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllPosts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllPostsRow
	for rows.Next() {
		var i GetAllPostsRow
		if err := rows.Scan(&i.ID, &i.UserID, &i.Content); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPostById = `-- name: GetPostById :one
SELECT
    id,
    user_id,
    content
FROM posts
WHERE id = $1 AND deleted_at = 0
`

type GetPostByIdRow struct {
	ID      int32
	UserID  int32
	Content string
}

func (q *Queries) GetPostById(ctx context.Context, id int32) (GetPostByIdRow, error) {
	row := q.db.QueryRowContext(ctx, getPostById, id)
	var i GetPostByIdRow
	err := row.Scan(&i.ID, &i.UserID, &i.Content)
	return i, err
}

const getPostByUserId = `-- name: GetPostByUserId :many
SELECT
    id,
    user_id,
    content
FROM posts
WHERE user_id = $1 AND deleted_at = 0
`

type GetPostByUserIdRow struct {
	ID      int32
	UserID  int32
	Content string
}

func (q *Queries) GetPostByUserId(ctx context.Context, userID int32) ([]GetPostByUserIdRow, error) {
	rows, err := q.db.QueryContext(ctx, getPostByUserId, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPostByUserIdRow
	for rows.Next() {
		var i GetPostByUserIdRow
		if err := rows.Scan(&i.ID, &i.UserID, &i.Content); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePost = `-- name: UpdatePost :exec
UPDATE posts
SET content = $2
WHERE id = $1 AND deleted_at = 0
`

type UpdatePostParams struct {
	ID      int32
	Content string
}

func (q *Queries) UpdatePost(ctx context.Context, arg UpdatePostParams) error {
	_, err := q.db.ExecContext(ctx, updatePost, arg.ID, arg.Content)
	return err
}
