// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.12
// source: protos/auth.proto

package authpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FirstName     string                 `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Phone         string                 `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	Email         string                 `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	Username      string                 `protobuf:"bytes,6,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,7,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_protos_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_protos_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_protos_auth_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *User) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *User) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *User) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type CheckCodeAfterUpdatePasswordReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckCodeAfterUpdatePasswordReq) Reset() {
	*x = CheckCodeAfterUpdatePasswordReq{}
	mi := &file_protos_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckCodeAfterUpdatePasswordReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckCodeAfterUpdatePasswordReq) ProtoMessage() {}

func (x *CheckCodeAfterUpdatePasswordReq) ProtoReflect() protoreflect.Message {
	mi := &file_protos_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckCodeAfterUpdatePasswordReq.ProtoReflect.Descriptor instead.
func (*CheckCodeAfterUpdatePasswordReq) Descriptor() ([]byte, []int) {
	return file_protos_auth_proto_rawDescGZIP(), []int{1}
}

func (x *CheckCodeAfterUpdatePasswordReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CheckCodeAfterUpdatePasswordReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type CheckCodeAfterUpdatePasswordResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        bool                   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckCodeAfterUpdatePasswordResp) Reset() {
	*x = CheckCodeAfterUpdatePasswordResp{}
	mi := &file_protos_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckCodeAfterUpdatePasswordResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckCodeAfterUpdatePasswordResp) ProtoMessage() {}

func (x *CheckCodeAfterUpdatePasswordResp) ProtoReflect() protoreflect.Message {
	mi := &file_protos_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckCodeAfterUpdatePasswordResp.ProtoReflect.Descriptor instead.
func (*CheckCodeAfterUpdatePasswordResp) Descriptor() ([]byte, []int) {
	return file_protos_auth_proto_rawDescGZIP(), []int{2}
}

func (x *CheckCodeAfterUpdatePasswordResp) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *CheckCodeAfterUpdatePasswordResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UpdatePasswordReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	NewPassword   string                 `protobuf:"bytes,2,opt,name=newPassword,proto3" json:"newPassword,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePasswordReq) Reset() {
	*x = UpdatePasswordReq{}
	mi := &file_protos_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePasswordReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePasswordReq) ProtoMessage() {}

func (x *UpdatePasswordReq) ProtoReflect() protoreflect.Message {
	mi := &file_protos_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePasswordReq.ProtoReflect.Descriptor instead.
func (*UpdatePasswordReq) Descriptor() ([]byte, []int) {
	return file_protos_auth_proto_rawDescGZIP(), []int{3}
}

func (x *UpdatePasswordReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdatePasswordReq) GetNewPassword() string {
	if x != nil {
		return x.NewPassword
	}
	return ""
}

type UpdatePasswordResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        bool                   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePasswordResp) Reset() {
	*x = UpdatePasswordResp{}
	mi := &file_protos_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePasswordResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePasswordResp) ProtoMessage() {}

func (x *UpdatePasswordResp) ProtoReflect() protoreflect.Message {
	mi := &file_protos_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePasswordResp.ProtoReflect.Descriptor instead.
func (*UpdatePasswordResp) Descriptor() ([]byte, []int) {
	return file_protos_auth_proto_rawDescGZIP(), []int{4}
}

func (x *UpdatePasswordResp) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *UpdatePasswordResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type SignInReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignInReq) Reset() {
	*x = SignInReq{}
	mi := &file_protos_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignInReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignInReq) ProtoMessage() {}

func (x *SignInReq) ProtoReflect() protoreflect.Message {
	mi := &file_protos_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignInReq.ProtoReflect.Descriptor instead.
func (*SignInReq) Descriptor() ([]byte, []int) {
	return file_protos_auth_proto_rawDescGZIP(), []int{5}
}

func (x *SignInReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *SignInReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type SignInResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        bool                   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Token         string                 `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignInResp) Reset() {
	*x = SignInResp{}
	mi := &file_protos_auth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignInResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignInResp) ProtoMessage() {}

func (x *SignInResp) ProtoReflect() protoreflect.Message {
	mi := &file_protos_auth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignInResp.ProtoReflect.Descriptor instead.
func (*SignInResp) Descriptor() ([]byte, []int) {
	return file_protos_auth_proto_rawDescGZIP(), []int{6}
}

func (x *SignInResp) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *SignInResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SignInResp) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type ForgetPasswordSendCodeEmailReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForgetPasswordSendCodeEmailReq) Reset() {
	*x = ForgetPasswordSendCodeEmailReq{}
	mi := &file_protos_auth_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForgetPasswordSendCodeEmailReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForgetPasswordSendCodeEmailReq) ProtoMessage() {}

func (x *ForgetPasswordSendCodeEmailReq) ProtoReflect() protoreflect.Message {
	mi := &file_protos_auth_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForgetPasswordSendCodeEmailReq.ProtoReflect.Descriptor instead.
func (*ForgetPasswordSendCodeEmailReq) Descriptor() ([]byte, []int) {
	return file_protos_auth_proto_rawDescGZIP(), []int{7}
}

func (x *ForgetPasswordSendCodeEmailReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type ForgetPasswordSendCodeEmailResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        bool                   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForgetPasswordSendCodeEmailResp) Reset() {
	*x = ForgetPasswordSendCodeEmailResp{}
	mi := &file_protos_auth_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForgetPasswordSendCodeEmailResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForgetPasswordSendCodeEmailResp) ProtoMessage() {}

func (x *ForgetPasswordSendCodeEmailResp) ProtoReflect() protoreflect.Message {
	mi := &file_protos_auth_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForgetPasswordSendCodeEmailResp.ProtoReflect.Descriptor instead.
func (*ForgetPasswordSendCodeEmailResp) Descriptor() ([]byte, []int) {
	return file_protos_auth_proto_rawDescGZIP(), []int{8}
}

func (x *ForgetPasswordSendCodeEmailResp) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *ForgetPasswordSendCodeEmailResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ForgetPasswordCheckCodeReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForgetPasswordCheckCodeReq) Reset() {
	*x = ForgetPasswordCheckCodeReq{}
	mi := &file_protos_auth_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForgetPasswordCheckCodeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForgetPasswordCheckCodeReq) ProtoMessage() {}

func (x *ForgetPasswordCheckCodeReq) ProtoReflect() protoreflect.Message {
	mi := &file_protos_auth_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForgetPasswordCheckCodeReq.ProtoReflect.Descriptor instead.
func (*ForgetPasswordCheckCodeReq) Descriptor() ([]byte, []int) {
	return file_protos_auth_proto_rawDescGZIP(), []int{9}
}

func (x *ForgetPasswordCheckCodeReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *ForgetPasswordCheckCodeReq) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type ForgetPasswordCheckCodeResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        bool                   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForgetPasswordCheckCodeResp) Reset() {
	*x = ForgetPasswordCheckCodeResp{}
	mi := &file_protos_auth_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForgetPasswordCheckCodeResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForgetPasswordCheckCodeResp) ProtoMessage() {}

func (x *ForgetPasswordCheckCodeResp) ProtoReflect() protoreflect.Message {
	mi := &file_protos_auth_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForgetPasswordCheckCodeResp.ProtoReflect.Descriptor instead.
func (*ForgetPasswordCheckCodeResp) Descriptor() ([]byte, []int) {
	return file_protos_auth_proto_rawDescGZIP(), []int{10}
}

func (x *ForgetPasswordCheckCodeResp) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *ForgetPasswordCheckCodeResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ForgetPasswordUpdatePasswordReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	NewPassword   string                 `protobuf:"bytes,2,opt,name=newPassword,proto3" json:"newPassword,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForgetPasswordUpdatePasswordReq) Reset() {
	*x = ForgetPasswordUpdatePasswordReq{}
	mi := &file_protos_auth_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForgetPasswordUpdatePasswordReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForgetPasswordUpdatePasswordReq) ProtoMessage() {}

func (x *ForgetPasswordUpdatePasswordReq) ProtoReflect() protoreflect.Message {
	mi := &file_protos_auth_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForgetPasswordUpdatePasswordReq.ProtoReflect.Descriptor instead.
func (*ForgetPasswordUpdatePasswordReq) Descriptor() ([]byte, []int) {
	return file_protos_auth_proto_rawDescGZIP(), []int{11}
}

func (x *ForgetPasswordUpdatePasswordReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *ForgetPasswordUpdatePasswordReq) GetNewPassword() string {
	if x != nil {
		return x.NewPassword
	}
	return ""
}

type ForgetPasswordUpdatePasswordResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        bool                   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForgetPasswordUpdatePasswordResp) Reset() {
	*x = ForgetPasswordUpdatePasswordResp{}
	mi := &file_protos_auth_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForgetPasswordUpdatePasswordResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForgetPasswordUpdatePasswordResp) ProtoMessage() {}

func (x *ForgetPasswordUpdatePasswordResp) ProtoReflect() protoreflect.Message {
	mi := &file_protos_auth_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForgetPasswordUpdatePasswordResp.ProtoReflect.Descriptor instead.
func (*ForgetPasswordUpdatePasswordResp) Descriptor() ([]byte, []int) {
	return file_protos_auth_proto_rawDescGZIP(), []int{12}
}

func (x *ForgetPasswordUpdatePasswordResp) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *ForgetPasswordUpdatePasswordResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CreateUserReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FirstName     string                 `protobuf:"bytes,1,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,2,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Phone         string                 `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	Email         string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Username      string                 `protobuf:"bytes,5,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,6,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserReq) Reset() {
	*x = CreateUserReq{}
	mi := &file_protos_auth_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserReq) ProtoMessage() {}

func (x *CreateUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_protos_auth_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserReq.ProtoReflect.Descriptor instead.
func (*CreateUserReq) Descriptor() ([]byte, []int) {
	return file_protos_auth_proto_rawDescGZIP(), []int{13}
}

func (x *CreateUserReq) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *CreateUserReq) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *CreateUserReq) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *CreateUserReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateUserReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *CreateUserReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type CreateUserResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        bool                   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserResp) Reset() {
	*x = CreateUserResp{}
	mi := &file_protos_auth_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserResp) ProtoMessage() {}

func (x *CreateUserResp) ProtoReflect() protoreflect.Message {
	mi := &file_protos_auth_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserResp.ProtoReflect.Descriptor instead.
func (*CreateUserResp) Descriptor() ([]byte, []int) {
	return file_protos_auth_proto_rawDescGZIP(), []int{14}
}

func (x *CreateUserResp) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *CreateUserResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UpdateUserReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FirstName     string                 `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Phone         string                 `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	Email         string                 `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	Username      string                 `protobuf:"bytes,6,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserReq) Reset() {
	*x = UpdateUserReq{}
	mi := &file_protos_auth_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserReq) ProtoMessage() {}

func (x *UpdateUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_protos_auth_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserReq.ProtoReflect.Descriptor instead.
func (*UpdateUserReq) Descriptor() ([]byte, []int) {
	return file_protos_auth_proto_rawDescGZIP(), []int{15}
}

func (x *UpdateUserReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateUserReq) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *UpdateUserReq) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *UpdateUserReq) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *UpdateUserReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UpdateUserReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type UpdateUserResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        bool                   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserResp) Reset() {
	*x = UpdateUserResp{}
	mi := &file_protos_auth_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserResp) ProtoMessage() {}

func (x *UpdateUserResp) ProtoReflect() protoreflect.Message {
	mi := &file_protos_auth_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserResp.ProtoReflect.Descriptor instead.
func (*UpdateUserResp) Descriptor() ([]byte, []int) {
	return file_protos_auth_proto_rawDescGZIP(), []int{16}
}

func (x *UpdateUserResp) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *UpdateUserResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DeleteUserReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserReq) Reset() {
	*x = DeleteUserReq{}
	mi := &file_protos_auth_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserReq) ProtoMessage() {}

func (x *DeleteUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_protos_auth_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserReq.ProtoReflect.Descriptor instead.
func (*DeleteUserReq) Descriptor() ([]byte, []int) {
	return file_protos_auth_proto_rawDescGZIP(), []int{17}
}

func (x *DeleteUserReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteUserResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        bool                   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserResp) Reset() {
	*x = DeleteUserResp{}
	mi := &file_protos_auth_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserResp) ProtoMessage() {}

func (x *DeleteUserResp) ProtoReflect() protoreflect.Message {
	mi := &file_protos_auth_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserResp.ProtoReflect.Descriptor instead.
func (*DeleteUserResp) Descriptor() ([]byte, []int) {
	return file_protos_auth_proto_rawDescGZIP(), []int{18}
}

func (x *DeleteUserResp) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *DeleteUserResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetUserByIdReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserByIdReq) Reset() {
	*x = GetUserByIdReq{}
	mi := &file_protos_auth_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserByIdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserByIdReq) ProtoMessage() {}

func (x *GetUserByIdReq) ProtoReflect() protoreflect.Message {
	mi := &file_protos_auth_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserByIdReq.ProtoReflect.Descriptor instead.
func (*GetUserByIdReq) Descriptor() ([]byte, []int) {
	return file_protos_auth_proto_rawDescGZIP(), []int{19}
}

func (x *GetUserByIdReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetUserByIdResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        bool                   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	User          *User                  `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserByIdResp) Reset() {
	*x = GetUserByIdResp{}
	mi := &file_protos_auth_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserByIdResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserByIdResp) ProtoMessage() {}

func (x *GetUserByIdResp) ProtoReflect() protoreflect.Message {
	mi := &file_protos_auth_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserByIdResp.ProtoReflect.Descriptor instead.
func (*GetUserByIdResp) Descriptor() ([]byte, []int) {
	return file_protos_auth_proto_rawDescGZIP(), []int{20}
}

func (x *GetUserByIdResp) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *GetUserByIdResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetUserByIdResp) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type GetUsersReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUsersReq) Reset() {
	*x = GetUsersReq{}
	mi := &file_protos_auth_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUsersReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsersReq) ProtoMessage() {}

func (x *GetUsersReq) ProtoReflect() protoreflect.Message {
	mi := &file_protos_auth_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsersReq.ProtoReflect.Descriptor instead.
func (*GetUsersReq) Descriptor() ([]byte, []int) {
	return file_protos_auth_proto_rawDescGZIP(), []int{21}
}

type GetUsersResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        bool                   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Users         []*User                `protobuf:"bytes,3,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUsersResp) Reset() {
	*x = GetUsersResp{}
	mi := &file_protos_auth_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUsersResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsersResp) ProtoMessage() {}

func (x *GetUsersResp) ProtoReflect() protoreflect.Message {
	mi := &file_protos_auth_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsersResp.ProtoReflect.Descriptor instead.
func (*GetUsersResp) Descriptor() ([]byte, []int) {
	return file_protos_auth_proto_rawDescGZIP(), []int{22}
}

func (x *GetUsersResp) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *GetUsersResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetUsersResp) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

var File_protos_auth_proto protoreflect.FileDescriptor

const file_protos_auth_proto_rawDesc = "" +
	"\n" +
	"\x11protos/auth.proto\"\xb6\x01\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"first_name\x18\x02 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x03 \x01(\tR\blastName\x12\x14\n" +
	"\x05phone\x18\x04 \x01(\tR\x05phone\x12\x14\n" +
	"\x05email\x18\x05 \x01(\tR\x05email\x12\x1a\n" +
	"\busername\x18\x06 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\a \x01(\tR\bpassword\"M\n" +
	"\x1fCheckCodeAfterUpdatePasswordReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"T\n" +
	" CheckCodeAfterUpdatePasswordResp\x12\x16\n" +
	"\x06status\x18\x01 \x01(\bR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"E\n" +
	"\x11UpdatePasswordReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12 \n" +
	"\vnewPassword\x18\x02 \x01(\tR\vnewPassword\"F\n" +
	"\x12UpdatePasswordResp\x12\x16\n" +
	"\x06status\x18\x01 \x01(\bR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"C\n" +
	"\tSignInReq\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"T\n" +
	"\n" +
	"SignInResp\x12\x16\n" +
	"\x06status\x18\x01 \x01(\bR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05token\"6\n" +
	"\x1eForgetPasswordSendCodeEmailReq\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\"S\n" +
	"\x1fForgetPasswordSendCodeEmailResp\x12\x16\n" +
	"\x06status\x18\x01 \x01(\bR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"F\n" +
	"\x1aForgetPasswordCheckCodeReq\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\"O\n" +
	"\x1bForgetPasswordCheckCodeResp\x12\x16\n" +
	"\x06status\x18\x01 \x01(\bR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"Y\n" +
	"\x1fForgetPasswordUpdatePasswordReq\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12 \n" +
	"\vnewPassword\x18\x02 \x01(\tR\vnewPassword\"T\n" +
	" ForgetPasswordUpdatePasswordResp\x12\x16\n" +
	"\x06status\x18\x01 \x01(\bR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xaf\x01\n" +
	"\rCreateUserReq\x12\x1d\n" +
	"\n" +
	"first_name\x18\x01 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x02 \x01(\tR\blastName\x12\x14\n" +
	"\x05phone\x18\x03 \x01(\tR\x05phone\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12\x1a\n" +
	"\busername\x18\x05 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x06 \x01(\tR\bpassword\"B\n" +
	"\x0eCreateUserResp\x12\x16\n" +
	"\x06status\x18\x01 \x01(\bR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xa3\x01\n" +
	"\rUpdateUserReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"first_name\x18\x02 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x03 \x01(\tR\blastName\x12\x14\n" +
	"\x05phone\x18\x04 \x01(\tR\x05phone\x12\x14\n" +
	"\x05email\x18\x05 \x01(\tR\x05email\x12\x1a\n" +
	"\busername\x18\x06 \x01(\tR\busername\"B\n" +
	"\x0eUpdateUserResp\x12\x16\n" +
	"\x06status\x18\x01 \x01(\bR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x1f\n" +
	"\rDeleteUserReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"B\n" +
	"\x0eDeleteUserResp\x12\x16\n" +
	"\x06status\x18\x01 \x01(\bR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\" \n" +
	"\x0eGetUserByIdReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"^\n" +
	"\x0fGetUserByIdResp\x12\x16\n" +
	"\x06status\x18\x01 \x01(\bR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x19\n" +
	"\x04user\x18\x03 \x01(\v2\x05.UserR\x04user\"\r\n" +
	"\vGetUsersReq\"]\n" +
	"\fGetUsersResp\x12\x16\n" +
	"\x06status\x18\x01 \x01(\bR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1b\n" +
	"\x05users\x18\x03 \x03(\v2\x05.UserR\x05users2\xd1\x05\n" +
	"\vUserService\x12!\n" +
	"\x06SignIn\x12\n" +
	".SignInReq\x1a\v.SignInResp\x12`\n" +
	"\x1bForgetPasswordSendCodeEmail\x12\x1f.ForgetPasswordSendCodeEmailReq\x1a .ForgetPasswordSendCodeEmailResp\x12T\n" +
	"\x17ForgetPasswordCheckCode\x12\x1b.ForgetPasswordCheckCodeReq\x1a\x1c.ForgetPasswordCheckCodeResp\x12c\n" +
	"\x1cForgetPasswordUpdatePassword\x12 .ForgetPasswordUpdatePasswordReq\x1a!.ForgetPasswordUpdatePasswordResp\x125\n" +
	"\x0eUpdatePassword\x12\x12.UpdatePasswordReq\x1a\x0f.UpdateUserResp\x12c\n" +
	"\x1cCheckCodeAfterUpdatePassword\x12 .CheckCodeAfterUpdatePasswordReq\x1a!.CheckCodeAfterUpdatePasswordResp\x12-\n" +
	"\n" +
	"CreateUser\x12\x0e.CreateUserReq\x1a\x0f.CreateUserResp\x12-\n" +
	"\n" +
	"UpdateUser\x12\x0e.UpdateUserReq\x1a\x0f.UpdateUserResp\x12-\n" +
	"\n" +
	"DeleteUser\x12\x0e.DeleteUserReq\x1a\x0f.DeleteUserResp\x120\n" +
	"\vGetUserById\x12\x0f.GetUserByIdReq\x1a\x10.GetUserByIdResp\x12'\n" +
	"\bGetUsers\x12\f.GetUsersReq\x1a\r.GetUsersRespB\x11Z\x0fgenproto/authpbb\x06proto3"

var (
	file_protos_auth_proto_rawDescOnce sync.Once
	file_protos_auth_proto_rawDescData []byte
)

func file_protos_auth_proto_rawDescGZIP() []byte {
	file_protos_auth_proto_rawDescOnce.Do(func() {
		file_protos_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_auth_proto_rawDesc), len(file_protos_auth_proto_rawDesc)))
	})
	return file_protos_auth_proto_rawDescData
}

var file_protos_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_protos_auth_proto_goTypes = []any{
	(*User)(nil),                             // 0: User
	(*CheckCodeAfterUpdatePasswordReq)(nil),  // 1: CheckCodeAfterUpdatePasswordReq
	(*CheckCodeAfterUpdatePasswordResp)(nil), // 2: CheckCodeAfterUpdatePasswordResp
	(*UpdatePasswordReq)(nil),                // 3: UpdatePasswordReq
	(*UpdatePasswordResp)(nil),               // 4: UpdatePasswordResp
	(*SignInReq)(nil),                        // 5: SignInReq
	(*SignInResp)(nil),                       // 6: SignInResp
	(*ForgetPasswordSendCodeEmailReq)(nil),   // 7: ForgetPasswordSendCodeEmailReq
	(*ForgetPasswordSendCodeEmailResp)(nil),  // 8: ForgetPasswordSendCodeEmailResp
	(*ForgetPasswordCheckCodeReq)(nil),       // 9: ForgetPasswordCheckCodeReq
	(*ForgetPasswordCheckCodeResp)(nil),      // 10: ForgetPasswordCheckCodeResp
	(*ForgetPasswordUpdatePasswordReq)(nil),  // 11: ForgetPasswordUpdatePasswordReq
	(*ForgetPasswordUpdatePasswordResp)(nil), // 12: ForgetPasswordUpdatePasswordResp
	(*CreateUserReq)(nil),                    // 13: CreateUserReq
	(*CreateUserResp)(nil),                   // 14: CreateUserResp
	(*UpdateUserReq)(nil),                    // 15: UpdateUserReq
	(*UpdateUserResp)(nil),                   // 16: UpdateUserResp
	(*DeleteUserReq)(nil),                    // 17: DeleteUserReq
	(*DeleteUserResp)(nil),                   // 18: DeleteUserResp
	(*GetUserByIdReq)(nil),                   // 19: GetUserByIdReq
	(*GetUserByIdResp)(nil),                  // 20: GetUserByIdResp
	(*GetUsersReq)(nil),                      // 21: GetUsersReq
	(*GetUsersResp)(nil),                     // 22: GetUsersResp
}
var file_protos_auth_proto_depIdxs = []int32{
	0,  // 0: GetUserByIdResp.user:type_name -> User
	0,  // 1: GetUsersResp.users:type_name -> User
	5,  // 2: UserService.SignIn:input_type -> SignInReq
	7,  // 3: UserService.ForgetPasswordSendCodeEmail:input_type -> ForgetPasswordSendCodeEmailReq
	9,  // 4: UserService.ForgetPasswordCheckCode:input_type -> ForgetPasswordCheckCodeReq
	11, // 5: UserService.ForgetPasswordUpdatePassword:input_type -> ForgetPasswordUpdatePasswordReq
	3,  // 6: UserService.UpdatePassword:input_type -> UpdatePasswordReq
	1,  // 7: UserService.CheckCodeAfterUpdatePassword:input_type -> CheckCodeAfterUpdatePasswordReq
	13, // 8: UserService.CreateUser:input_type -> CreateUserReq
	15, // 9: UserService.UpdateUser:input_type -> UpdateUserReq
	17, // 10: UserService.DeleteUser:input_type -> DeleteUserReq
	19, // 11: UserService.GetUserById:input_type -> GetUserByIdReq
	21, // 12: UserService.GetUsers:input_type -> GetUsersReq
	6,  // 13: UserService.SignIn:output_type -> SignInResp
	8,  // 14: UserService.ForgetPasswordSendCodeEmail:output_type -> ForgetPasswordSendCodeEmailResp
	10, // 15: UserService.ForgetPasswordCheckCode:output_type -> ForgetPasswordCheckCodeResp
	12, // 16: UserService.ForgetPasswordUpdatePassword:output_type -> ForgetPasswordUpdatePasswordResp
	16, // 17: UserService.UpdatePassword:output_type -> UpdateUserResp
	2,  // 18: UserService.CheckCodeAfterUpdatePassword:output_type -> CheckCodeAfterUpdatePasswordResp
	14, // 19: UserService.CreateUser:output_type -> CreateUserResp
	16, // 20: UserService.UpdateUser:output_type -> UpdateUserResp
	18, // 21: UserService.DeleteUser:output_type -> DeleteUserResp
	20, // 22: UserService.GetUserById:output_type -> GetUserByIdResp
	22, // 23: UserService.GetUsers:output_type -> GetUsersResp
	13, // [13:24] is the sub-list for method output_type
	2,  // [2:13] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_protos_auth_proto_init() }
func file_protos_auth_proto_init() {
	if File_protos_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_auth_proto_rawDesc), len(file_protos_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_auth_proto_goTypes,
		DependencyIndexes: file_protos_auth_proto_depIdxs,
		MessageInfos:      file_protos_auth_proto_msgTypes,
	}.Build()
	File_protos_auth_proto = out.File
	file_protos_auth_proto_goTypes = nil
	file_protos_auth_proto_depIdxs = nil
}
