// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.12
// source: protos/comment.proto

package commentpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Comment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PostId        string                 `protobuf:"bytes,3,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Comment) Reset() {
	*x = Comment{}
	mi := &file_protos_comment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Comment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Comment) ProtoMessage() {}

func (x *Comment) ProtoReflect() protoreflect.Message {
	mi := &file_protos_comment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Comment.ProtoReflect.Descriptor instead.
func (*Comment) Descriptor() ([]byte, []int) {
	return file_protos_comment_proto_rawDescGZIP(), []int{0}
}

func (x *Comment) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Comment) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Comment) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

func (x *Comment) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type CreateCommentReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PostId        string                 `protobuf:"bytes,2,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCommentReq) Reset() {
	*x = CreateCommentReq{}
	mi := &file_protos_comment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCommentReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCommentReq) ProtoMessage() {}

func (x *CreateCommentReq) ProtoReflect() protoreflect.Message {
	mi := &file_protos_comment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCommentReq.ProtoReflect.Descriptor instead.
func (*CreateCommentReq) Descriptor() ([]byte, []int) {
	return file_protos_comment_proto_rawDescGZIP(), []int{1}
}

func (x *CreateCommentReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateCommentReq) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

func (x *CreateCommentReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type CreateCommentResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        bool                   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCommentResp) Reset() {
	*x = CreateCommentResp{}
	mi := &file_protos_comment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCommentResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCommentResp) ProtoMessage() {}

func (x *CreateCommentResp) ProtoReflect() protoreflect.Message {
	mi := &file_protos_comment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCommentResp.ProtoReflect.Descriptor instead.
func (*CreateCommentResp) Descriptor() ([]byte, []int) {
	return file_protos_comment_proto_rawDescGZIP(), []int{2}
}

func (x *CreateCommentResp) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *CreateCommentResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UpdateCommentReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCommentReq) Reset() {
	*x = UpdateCommentReq{}
	mi := &file_protos_comment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCommentReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCommentReq) ProtoMessage() {}

func (x *UpdateCommentReq) ProtoReflect() protoreflect.Message {
	mi := &file_protos_comment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCommentReq.ProtoReflect.Descriptor instead.
func (*UpdateCommentReq) Descriptor() ([]byte, []int) {
	return file_protos_comment_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateCommentReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateCommentReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type UpdateCommentResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        bool                   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCommentResp) Reset() {
	*x = UpdateCommentResp{}
	mi := &file_protos_comment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCommentResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCommentResp) ProtoMessage() {}

func (x *UpdateCommentResp) ProtoReflect() protoreflect.Message {
	mi := &file_protos_comment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCommentResp.ProtoReflect.Descriptor instead.
func (*UpdateCommentResp) Descriptor() ([]byte, []int) {
	return file_protos_comment_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateCommentResp) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *UpdateCommentResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DeleteCommentReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCommentReq) Reset() {
	*x = DeleteCommentReq{}
	mi := &file_protos_comment_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCommentReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCommentReq) ProtoMessage() {}

func (x *DeleteCommentReq) ProtoReflect() protoreflect.Message {
	mi := &file_protos_comment_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCommentReq.ProtoReflect.Descriptor instead.
func (*DeleteCommentReq) Descriptor() ([]byte, []int) {
	return file_protos_comment_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteCommentReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteCommentResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        bool                   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCommentResp) Reset() {
	*x = DeleteCommentResp{}
	mi := &file_protos_comment_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCommentResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCommentResp) ProtoMessage() {}

func (x *DeleteCommentResp) ProtoReflect() protoreflect.Message {
	mi := &file_protos_comment_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCommentResp.ProtoReflect.Descriptor instead.
func (*DeleteCommentResp) Descriptor() ([]byte, []int) {
	return file_protos_comment_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteCommentResp) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *DeleteCommentResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetCommentByUserIdReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCommentByUserIdReq) Reset() {
	*x = GetCommentByUserIdReq{}
	mi := &file_protos_comment_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCommentByUserIdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommentByUserIdReq) ProtoMessage() {}

func (x *GetCommentByUserIdReq) ProtoReflect() protoreflect.Message {
	mi := &file_protos_comment_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommentByUserIdReq.ProtoReflect.Descriptor instead.
func (*GetCommentByUserIdReq) Descriptor() ([]byte, []int) {
	return file_protos_comment_proto_rawDescGZIP(), []int{7}
}

func (x *GetCommentByUserIdReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetCommentByUserIdResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        bool                   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Comments      []*Comment             `protobuf:"bytes,3,rep,name=comments,proto3" json:"comments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCommentByUserIdResp) Reset() {
	*x = GetCommentByUserIdResp{}
	mi := &file_protos_comment_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCommentByUserIdResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommentByUserIdResp) ProtoMessage() {}

func (x *GetCommentByUserIdResp) ProtoReflect() protoreflect.Message {
	mi := &file_protos_comment_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommentByUserIdResp.ProtoReflect.Descriptor instead.
func (*GetCommentByUserIdResp) Descriptor() ([]byte, []int) {
	return file_protos_comment_proto_rawDescGZIP(), []int{8}
}

func (x *GetCommentByUserIdResp) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *GetCommentByUserIdResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetCommentByUserIdResp) GetComments() []*Comment {
	if x != nil {
		return x.Comments
	}
	return nil
}

type GetCommentByPostIdReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        string                 `protobuf:"bytes,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCommentByPostIdReq) Reset() {
	*x = GetCommentByPostIdReq{}
	mi := &file_protos_comment_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCommentByPostIdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommentByPostIdReq) ProtoMessage() {}

func (x *GetCommentByPostIdReq) ProtoReflect() protoreflect.Message {
	mi := &file_protos_comment_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommentByPostIdReq.ProtoReflect.Descriptor instead.
func (*GetCommentByPostIdReq) Descriptor() ([]byte, []int) {
	return file_protos_comment_proto_rawDescGZIP(), []int{9}
}

func (x *GetCommentByPostIdReq) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

type GetCommentByPostIdResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        bool                   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Comments      []*Comment             `protobuf:"bytes,3,rep,name=comments,proto3" json:"comments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCommentByPostIdResp) Reset() {
	*x = GetCommentByPostIdResp{}
	mi := &file_protos_comment_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCommentByPostIdResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommentByPostIdResp) ProtoMessage() {}

func (x *GetCommentByPostIdResp) ProtoReflect() protoreflect.Message {
	mi := &file_protos_comment_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommentByPostIdResp.ProtoReflect.Descriptor instead.
func (*GetCommentByPostIdResp) Descriptor() ([]byte, []int) {
	return file_protos_comment_proto_rawDescGZIP(), []int{10}
}

func (x *GetCommentByPostIdResp) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *GetCommentByPostIdResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetCommentByPostIdResp) GetComments() []*Comment {
	if x != nil {
		return x.Comments
	}
	return nil
}

var File_protos_comment_proto protoreflect.FileDescriptor

const file_protos_comment_proto_rawDesc = "" +
	"\n" +
	"\x14protos/comment.proto\"e\n" +
	"\aComment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x17\n" +
	"\apost_id\x18\x03 \x01(\tR\x06postId\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\"^\n" +
	"\x10CreateCommentReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x17\n" +
	"\apost_id\x18\x02 \x01(\tR\x06postId\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\"E\n" +
	"\x11CreateCommentResp\x12\x16\n" +
	"\x06status\x18\x01 \x01(\bR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"<\n" +
	"\x10UpdateCommentReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"E\n" +
	"\x11UpdateCommentResp\x12\x16\n" +
	"\x06status\x18\x01 \x01(\bR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\"\n" +
	"\x10DeleteCommentReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"E\n" +
	"\x11DeleteCommentResp\x12\x16\n" +
	"\x06status\x18\x01 \x01(\bR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"0\n" +
	"\x15GetCommentByUserIdReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"p\n" +
	"\x16GetCommentByUserIdResp\x12\x16\n" +
	"\x06status\x18\x01 \x01(\bR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12$\n" +
	"\bcomments\x18\x03 \x03(\v2\b.CommentR\bcomments\"0\n" +
	"\x15GetCommentByPostIdReq\x12\x17\n" +
	"\apost_id\x18\x01 \x01(\tR\x06postId\"p\n" +
	"\x16GetCommentByPostIdResp\x12\x16\n" +
	"\x06status\x18\x01 \x01(\bR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12$\n" +
	"\bcomments\x18\x03 \x03(\v2\b.CommentR\bcomments2\xc6\x02\n" +
	"\x0eCommentService\x126\n" +
	"\rCreateComment\x12\x11.CreateCommentReq\x1a\x12.CreateCommentResp\x126\n" +
	"\rUpdateComment\x12\x11.UpdateCommentReq\x1a\x12.UpdateCommentResp\x126\n" +
	"\rDeleteComment\x12\x11.DeleteCommentReq\x1a\x12.DeleteCommentResp\x12E\n" +
	"\x12GetCommentByUserId\x12\x16.GetCommentByUserIdReq\x1a\x17.GetCommentByUserIdResp\x12E\n" +
	"\x12GetCommentByPostId\x12\x16.GetCommentByPostIdReq\x1a\x17.GetCommentByPostIdRespB\x14Z\x12genproto/commentpbb\x06proto3"

var (
	file_protos_comment_proto_rawDescOnce sync.Once
	file_protos_comment_proto_rawDescData []byte
)

func file_protos_comment_proto_rawDescGZIP() []byte {
	file_protos_comment_proto_rawDescOnce.Do(func() {
		file_protos_comment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_comment_proto_rawDesc), len(file_protos_comment_proto_rawDesc)))
	})
	return file_protos_comment_proto_rawDescData
}

var file_protos_comment_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_protos_comment_proto_goTypes = []any{
	(*Comment)(nil),                // 0: Comment
	(*CreateCommentReq)(nil),       // 1: CreateCommentReq
	(*CreateCommentResp)(nil),      // 2: CreateCommentResp
	(*UpdateCommentReq)(nil),       // 3: UpdateCommentReq
	(*UpdateCommentResp)(nil),      // 4: UpdateCommentResp
	(*DeleteCommentReq)(nil),       // 5: DeleteCommentReq
	(*DeleteCommentResp)(nil),      // 6: DeleteCommentResp
	(*GetCommentByUserIdReq)(nil),  // 7: GetCommentByUserIdReq
	(*GetCommentByUserIdResp)(nil), // 8: GetCommentByUserIdResp
	(*GetCommentByPostIdReq)(nil),  // 9: GetCommentByPostIdReq
	(*GetCommentByPostIdResp)(nil), // 10: GetCommentByPostIdResp
}
var file_protos_comment_proto_depIdxs = []int32{
	0,  // 0: GetCommentByUserIdResp.comments:type_name -> Comment
	0,  // 1: GetCommentByPostIdResp.comments:type_name -> Comment
	1,  // 2: CommentService.CreateComment:input_type -> CreateCommentReq
	3,  // 3: CommentService.UpdateComment:input_type -> UpdateCommentReq
	5,  // 4: CommentService.DeleteComment:input_type -> DeleteCommentReq
	7,  // 5: CommentService.GetCommentByUserId:input_type -> GetCommentByUserIdReq
	9,  // 6: CommentService.GetCommentByPostId:input_type -> GetCommentByPostIdReq
	2,  // 7: CommentService.CreateComment:output_type -> CreateCommentResp
	4,  // 8: CommentService.UpdateComment:output_type -> UpdateCommentResp
	6,  // 9: CommentService.DeleteComment:output_type -> DeleteCommentResp
	8,  // 10: CommentService.GetCommentByUserId:output_type -> GetCommentByUserIdResp
	10, // 11: CommentService.GetCommentByPostId:output_type -> GetCommentByPostIdResp
	7,  // [7:12] is the sub-list for method output_type
	2,  // [2:7] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_protos_comment_proto_init() }
func file_protos_comment_proto_init() {
	if File_protos_comment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_comment_proto_rawDesc), len(file_protos_comment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_comment_proto_goTypes,
		DependencyIndexes: file_protos_comment_proto_depIdxs,
		MessageInfos:      file_protos_comment_proto_msgTypes,
	}.Build()
	File_protos_comment_proto = out.File
	file_protos_comment_proto_goTypes = nil
	file_protos_comment_proto_depIdxs = nil
}
