// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: protos/course.proto

package coursepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CourseService_CreateCourse_FullMethodName         = "/CourseService/CreateCourse"
	CourseService_UpdateCourse_FullMethodName         = "/CourseService/UpdateCourse"
	CourseService_DeleteCourse_FullMethodName         = "/CourseService/DeleteCourse"
	CourseService_GetCourseById_FullMethodName        = "/CourseService/GetCourseById"
	CourseService_GetCourses_FullMethodName           = "/CourseService/GetCourses"
	CourseService_GetCourseByUserId_FullMethodName    = "/CourseService/GetCourseByUserId"
	CourseService_CreateLesson_FullMethodName         = "/CourseService/CreateLesson"
	CourseService_UpdateLesson_FullMethodName         = "/CourseService/UpdateLesson"
	CourseService_DeleteLesson_FullMethodName         = "/CourseService/DeleteLesson"
	CourseService_GetLessonById_FullMethodName        = "/CourseService/GetLessonById"
	CourseService_GetLessonsByCourseId_FullMethodName = "/CourseService/GetLessonsByCourseId"
)

// CourseServiceClient is the client API for CourseService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CourseServiceClient interface {
	CreateCourse(ctx context.Context, in *CreateCourseReq, opts ...grpc.CallOption) (*CreateCourseResp, error)
	UpdateCourse(ctx context.Context, in *UpdateCourseReq, opts ...grpc.CallOption) (*UpdateCourseResp, error)
	DeleteCourse(ctx context.Context, in *DeleteCourseReq, opts ...grpc.CallOption) (*DeleteCourseResp, error)
	GetCourseById(ctx context.Context, in *GetCourseByIdReq, opts ...grpc.CallOption) (*GetCourseByIdResp, error)
	GetCourses(ctx context.Context, in *GetCoursesReq, opts ...grpc.CallOption) (*GetCoursesResp, error)
	GetCourseByUserId(ctx context.Context, in *GetCourseByUserIdReq, opts ...grpc.CallOption) (*GetCourseByUserIdResp, error)
	CreateLesson(ctx context.Context, in *CreateLessonReq, opts ...grpc.CallOption) (*CreateLessonResp, error)
	UpdateLesson(ctx context.Context, in *UpdateLessonReq, opts ...grpc.CallOption) (*UpdateLessonResp, error)
	DeleteLesson(ctx context.Context, in *DeleteLessonReq, opts ...grpc.CallOption) (*DeleteLessonResp, error)
	GetLessonById(ctx context.Context, in *GetLessonByIdReq, opts ...grpc.CallOption) (*GetLessonByIdResp, error)
	GetLessonsByCourseId(ctx context.Context, in *GetLessonsByCourseIdReq, opts ...grpc.CallOption) (*GetLessonsByCourseIdResp, error)
}

type courseServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCourseServiceClient(cc grpc.ClientConnInterface) CourseServiceClient {
	return &courseServiceClient{cc}
}

func (c *courseServiceClient) CreateCourse(ctx context.Context, in *CreateCourseReq, opts ...grpc.CallOption) (*CreateCourseResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateCourseResp)
	err := c.cc.Invoke(ctx, CourseService_CreateCourse_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *courseServiceClient) UpdateCourse(ctx context.Context, in *UpdateCourseReq, opts ...grpc.CallOption) (*UpdateCourseResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateCourseResp)
	err := c.cc.Invoke(ctx, CourseService_UpdateCourse_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *courseServiceClient) DeleteCourse(ctx context.Context, in *DeleteCourseReq, opts ...grpc.CallOption) (*DeleteCourseResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteCourseResp)
	err := c.cc.Invoke(ctx, CourseService_DeleteCourse_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *courseServiceClient) GetCourseById(ctx context.Context, in *GetCourseByIdReq, opts ...grpc.CallOption) (*GetCourseByIdResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCourseByIdResp)
	err := c.cc.Invoke(ctx, CourseService_GetCourseById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *courseServiceClient) GetCourses(ctx context.Context, in *GetCoursesReq, opts ...grpc.CallOption) (*GetCoursesResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCoursesResp)
	err := c.cc.Invoke(ctx, CourseService_GetCourses_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *courseServiceClient) GetCourseByUserId(ctx context.Context, in *GetCourseByUserIdReq, opts ...grpc.CallOption) (*GetCourseByUserIdResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCourseByUserIdResp)
	err := c.cc.Invoke(ctx, CourseService_GetCourseByUserId_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *courseServiceClient) CreateLesson(ctx context.Context, in *CreateLessonReq, opts ...grpc.CallOption) (*CreateLessonResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateLessonResp)
	err := c.cc.Invoke(ctx, CourseService_CreateLesson_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *courseServiceClient) UpdateLesson(ctx context.Context, in *UpdateLessonReq, opts ...grpc.CallOption) (*UpdateLessonResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateLessonResp)
	err := c.cc.Invoke(ctx, CourseService_UpdateLesson_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *courseServiceClient) DeleteLesson(ctx context.Context, in *DeleteLessonReq, opts ...grpc.CallOption) (*DeleteLessonResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteLessonResp)
	err := c.cc.Invoke(ctx, CourseService_DeleteLesson_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *courseServiceClient) GetLessonById(ctx context.Context, in *GetLessonByIdReq, opts ...grpc.CallOption) (*GetLessonByIdResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLessonByIdResp)
	err := c.cc.Invoke(ctx, CourseService_GetLessonById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *courseServiceClient) GetLessonsByCourseId(ctx context.Context, in *GetLessonsByCourseIdReq, opts ...grpc.CallOption) (*GetLessonsByCourseIdResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLessonsByCourseIdResp)
	err := c.cc.Invoke(ctx, CourseService_GetLessonsByCourseId_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CourseServiceServer is the server API for CourseService service.
// All implementations must embed UnimplementedCourseServiceServer
// for forward compatibility.
type CourseServiceServer interface {
	CreateCourse(context.Context, *CreateCourseReq) (*CreateCourseResp, error)
	UpdateCourse(context.Context, *UpdateCourseReq) (*UpdateCourseResp, error)
	DeleteCourse(context.Context, *DeleteCourseReq) (*DeleteCourseResp, error)
	GetCourseById(context.Context, *GetCourseByIdReq) (*GetCourseByIdResp, error)
	GetCourses(context.Context, *GetCoursesReq) (*GetCoursesResp, error)
	GetCourseByUserId(context.Context, *GetCourseByUserIdReq) (*GetCourseByUserIdResp, error)
	CreateLesson(context.Context, *CreateLessonReq) (*CreateLessonResp, error)
	UpdateLesson(context.Context, *UpdateLessonReq) (*UpdateLessonResp, error)
	DeleteLesson(context.Context, *DeleteLessonReq) (*DeleteLessonResp, error)
	GetLessonById(context.Context, *GetLessonByIdReq) (*GetLessonByIdResp, error)
	GetLessonsByCourseId(context.Context, *GetLessonsByCourseIdReq) (*GetLessonsByCourseIdResp, error)
	mustEmbedUnimplementedCourseServiceServer()
}

// UnimplementedCourseServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCourseServiceServer struct{}

func (UnimplementedCourseServiceServer) CreateCourse(context.Context, *CreateCourseReq) (*CreateCourseResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCourse not implemented")
}
func (UnimplementedCourseServiceServer) UpdateCourse(context.Context, *UpdateCourseReq) (*UpdateCourseResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateCourse not implemented")
}
func (UnimplementedCourseServiceServer) DeleteCourse(context.Context, *DeleteCourseReq) (*DeleteCourseResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteCourse not implemented")
}
func (UnimplementedCourseServiceServer) GetCourseById(context.Context, *GetCourseByIdReq) (*GetCourseByIdResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCourseById not implemented")
}
func (UnimplementedCourseServiceServer) GetCourses(context.Context, *GetCoursesReq) (*GetCoursesResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCourses not implemented")
}
func (UnimplementedCourseServiceServer) GetCourseByUserId(context.Context, *GetCourseByUserIdReq) (*GetCourseByUserIdResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCourseByUserId not implemented")
}
func (UnimplementedCourseServiceServer) CreateLesson(context.Context, *CreateLessonReq) (*CreateLessonResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateLesson not implemented")
}
func (UnimplementedCourseServiceServer) UpdateLesson(context.Context, *UpdateLessonReq) (*UpdateLessonResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateLesson not implemented")
}
func (UnimplementedCourseServiceServer) DeleteLesson(context.Context, *DeleteLessonReq) (*DeleteLessonResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteLesson not implemented")
}
func (UnimplementedCourseServiceServer) GetLessonById(context.Context, *GetLessonByIdReq) (*GetLessonByIdResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLessonById not implemented")
}
func (UnimplementedCourseServiceServer) GetLessonsByCourseId(context.Context, *GetLessonsByCourseIdReq) (*GetLessonsByCourseIdResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLessonsByCourseId not implemented")
}
func (UnimplementedCourseServiceServer) mustEmbedUnimplementedCourseServiceServer() {}
func (UnimplementedCourseServiceServer) testEmbeddedByValue()                       {}

// UnsafeCourseServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CourseServiceServer will
// result in compilation errors.
type UnsafeCourseServiceServer interface {
	mustEmbedUnimplementedCourseServiceServer()
}

func RegisterCourseServiceServer(s grpc.ServiceRegistrar, srv CourseServiceServer) {
	// If the following call pancis, it indicates UnimplementedCourseServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CourseService_ServiceDesc, srv)
}

func _CourseService_CreateCourse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCourseReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CourseServiceServer).CreateCourse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CourseService_CreateCourse_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CourseServiceServer).CreateCourse(ctx, req.(*CreateCourseReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CourseService_UpdateCourse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCourseReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CourseServiceServer).UpdateCourse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CourseService_UpdateCourse_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CourseServiceServer).UpdateCourse(ctx, req.(*UpdateCourseReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CourseService_DeleteCourse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCourseReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CourseServiceServer).DeleteCourse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CourseService_DeleteCourse_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CourseServiceServer).DeleteCourse(ctx, req.(*DeleteCourseReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CourseService_GetCourseById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCourseByIdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CourseServiceServer).GetCourseById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CourseService_GetCourseById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CourseServiceServer).GetCourseById(ctx, req.(*GetCourseByIdReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CourseService_GetCourses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCoursesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CourseServiceServer).GetCourses(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CourseService_GetCourses_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CourseServiceServer).GetCourses(ctx, req.(*GetCoursesReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CourseService_GetCourseByUserId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCourseByUserIdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CourseServiceServer).GetCourseByUserId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CourseService_GetCourseByUserId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CourseServiceServer).GetCourseByUserId(ctx, req.(*GetCourseByUserIdReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CourseService_CreateLesson_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateLessonReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CourseServiceServer).CreateLesson(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CourseService_CreateLesson_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CourseServiceServer).CreateLesson(ctx, req.(*CreateLessonReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CourseService_UpdateLesson_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateLessonReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CourseServiceServer).UpdateLesson(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CourseService_UpdateLesson_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CourseServiceServer).UpdateLesson(ctx, req.(*UpdateLessonReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CourseService_DeleteLesson_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteLessonReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CourseServiceServer).DeleteLesson(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CourseService_DeleteLesson_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CourseServiceServer).DeleteLesson(ctx, req.(*DeleteLessonReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CourseService_GetLessonById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLessonByIdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CourseServiceServer).GetLessonById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CourseService_GetLessonById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CourseServiceServer).GetLessonById(ctx, req.(*GetLessonByIdReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CourseService_GetLessonsByCourseId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLessonsByCourseIdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CourseServiceServer).GetLessonsByCourseId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CourseService_GetLessonsByCourseId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CourseServiceServer).GetLessonsByCourseId(ctx, req.(*GetLessonsByCourseIdReq))
	}
	return interceptor(ctx, in, info, handler)
}

// CourseService_ServiceDesc is the grpc.ServiceDesc for CourseService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CourseService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "CourseService",
	HandlerType: (*CourseServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateCourse",
			Handler:    _CourseService_CreateCourse_Handler,
		},
		{
			MethodName: "UpdateCourse",
			Handler:    _CourseService_UpdateCourse_Handler,
		},
		{
			MethodName: "DeleteCourse",
			Handler:    _CourseService_DeleteCourse_Handler,
		},
		{
			MethodName: "GetCourseById",
			Handler:    _CourseService_GetCourseById_Handler,
		},
		{
			MethodName: "GetCourses",
			Handler:    _CourseService_GetCourses_Handler,
		},
		{
			MethodName: "GetCourseByUserId",
			Handler:    _CourseService_GetCourseByUserId_Handler,
		},
		{
			MethodName: "CreateLesson",
			Handler:    _CourseService_CreateLesson_Handler,
		},
		{
			MethodName: "UpdateLesson",
			Handler:    _CourseService_UpdateLesson_Handler,
		},
		{
			MethodName: "DeleteLesson",
			Handler:    _CourseService_DeleteLesson_Handler,
		},
		{
			MethodName: "GetLessonById",
			Handler:    _CourseService_GetLessonById_Handler,
		},
		{
			MethodName: "GetLessonsByCourseId",
			Handler:    _CourseService_GetLessonsByCourseId_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/course.proto",
}
