// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package storage

import (
	"database/sql"
)

type Like struct {
	ID        int32
	UserID    int32
	PostID    int32
	CreatedAt sql.NullTime
}
