// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package storage

import (
	"context"
)

const addLike = `-- name: AddLike :exec
INSERT INTO likes(user_id, post_id) VALUES ($1, $2)
`

type AddLikeParams struct {
	UserID int32
	PostID int32
}

func (q *Queries) AddLike(ctx context.Context, arg AddLikeParams) error {
	_, err := q.db.ExecContext(ctx, addLike, arg.UserID, arg.PostID)
	return err
}

const checkLike = `-- name: CheckLike :one
SELECT EXISTS(
    SELECT 1 FROM likes
    WHERE user_id = $1 AND post_id = $2
)
`

type CheckLikeParams struct {
	UserID int32
	PostID int32
}

func (q *Queries) CheckLike(ctx context.Context, arg CheckLikeParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, checkLike, arg.UserID, arg.PostID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const removeLike = `-- name: RemoveLike :exec
DELETE FROM likes WHERE user_id=$1 AND post_id=$2
`

type RemoveLikeParams struct {
	UserID int32
	PostID int32
}

func (q *Queries) RemoveLike(ctx context.Context, arg RemoveLikeParams) error {
	_, err := q.db.ExecContext(ctx, removeLike, arg.UserID, arg.PostID)
	return err
}
