// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.12
// source: protos/like.proto

package likepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Like struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PostId        string                 `protobuf:"bytes,3,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Like) Reset() {
	*x = Like{}
	mi := &file_protos_like_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Like) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Like) ProtoMessage() {}

func (x *Like) ProtoReflect() protoreflect.Message {
	mi := &file_protos_like_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Like.ProtoReflect.Descriptor instead.
func (*Like) Descriptor() ([]byte, []int) {
	return file_protos_like_proto_rawDescGZIP(), []int{0}
}

func (x *Like) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Like) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Like) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

type ToggleLikeReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PostId        string                 `protobuf:"bytes,2,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToggleLikeReq) Reset() {
	*x = ToggleLikeReq{}
	mi := &file_protos_like_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToggleLikeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToggleLikeReq) ProtoMessage() {}

func (x *ToggleLikeReq) ProtoReflect() protoreflect.Message {
	mi := &file_protos_like_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToggleLikeReq.ProtoReflect.Descriptor instead.
func (*ToggleLikeReq) Descriptor() ([]byte, []int) {
	return file_protos_like_proto_rawDescGZIP(), []int{1}
}

func (x *ToggleLikeReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ToggleLikeReq) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

type ToggleLikeResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        bool                   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToggleLikeResp) Reset() {
	*x = ToggleLikeResp{}
	mi := &file_protos_like_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToggleLikeResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToggleLikeResp) ProtoMessage() {}

func (x *ToggleLikeResp) ProtoReflect() protoreflect.Message {
	mi := &file_protos_like_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToggleLikeResp.ProtoReflect.Descriptor instead.
func (*ToggleLikeResp) Descriptor() ([]byte, []int) {
	return file_protos_like_proto_rawDescGZIP(), []int{2}
}

func (x *ToggleLikeResp) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *ToggleLikeResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_protos_like_proto protoreflect.FileDescriptor

const file_protos_like_proto_rawDesc = "" +
	"\n" +
	"\x11protos/like.proto\"H\n" +
	"\x04Like\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x17\n" +
	"\apost_id\x18\x03 \x01(\tR\x06postId\"A\n" +
	"\rToggleLikeReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x17\n" +
	"\apost_id\x18\x02 \x01(\tR\x06postId\"B\n" +
	"\x0eToggleLikeResp\x12\x16\n" +
	"\x06status\x18\x01 \x01(\bR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2<\n" +
	"\vLikeService\x12-\n" +
	"\n" +
	"ToggleLike\x12\x0e.ToggleLikeReq\x1a\x0f.ToggleLikeRespB\x11Z\x0fgenproto/likepbb\x06proto3"

var (
	file_protos_like_proto_rawDescOnce sync.Once
	file_protos_like_proto_rawDescData []byte
)

func file_protos_like_proto_rawDescGZIP() []byte {
	file_protos_like_proto_rawDescOnce.Do(func() {
		file_protos_like_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_like_proto_rawDesc), len(file_protos_like_proto_rawDesc)))
	})
	return file_protos_like_proto_rawDescData
}

var file_protos_like_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_protos_like_proto_goTypes = []any{
	(*Like)(nil),           // 0: Like
	(*ToggleLikeReq)(nil),  // 1: ToggleLikeReq
	(*ToggleLikeResp)(nil), // 2: ToggleLikeResp
}
var file_protos_like_proto_depIdxs = []int32{
	1, // 0: LikeService.ToggleLike:input_type -> ToggleLikeReq
	2, // 1: LikeService.ToggleLike:output_type -> ToggleLikeResp
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protos_like_proto_init() }
func file_protos_like_proto_init() {
	if File_protos_like_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_like_proto_rawDesc), len(file_protos_like_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_like_proto_goTypes,
		DependencyIndexes: file_protos_like_proto_depIdxs,
		MessageInfos:      file_protos_like_proto_msgTypes,
	}.Build()
	File_protos_like_proto = out.File
	file_protos_like_proto_goTypes = nil
	file_protos_like_proto_depIdxs = nil
}
